In [1]:
import warnings
warnings.filterwarnings("ignore")

import os
import sys
import json
import math
import time
import getpass
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd

from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

import psycopg2
from psycopg2 import sql

from IPython.display import display, Markdown

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 300)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

PROJECT_ROOT = Path(r"C:\Users\asus\Documents\ECOMMERCE-AI-PLATFORM")

DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
PREDICTIONS_DIR = DATA_DIR / "predictions"

NOTEBOOK_DIR = PROJECT_ROOT / "notebooks"

for directory in [
    DATA_DIR,
    RAW_DATA_DIR,
    PROCESSED_DATA_DIR,
    PREDICTIONS_DIR,
]:
    directory.mkdir(parents=True, exist_ok=True)

DB_CONFIG = {
    "host": "localhost",
    "port": 5432,
    "database": "ecommerce_ai_db",
    "user": input("PostgreSQL Username: ").strip(),
    "password": getpass.getpass("PostgreSQL Password: ")
}

CURRENT_TIMESTAMP = datetime.now()

print("=" * 80)
print("ECOMMERCE-AI-PLATFORM")
print("Notebook 14 - AI Business Insights Engine")
print("=" * 80)

print(f"Project Root : {PROJECT_ROOT}")
print(f"Database     : {DB_CONFIG['database']}")
print(f"Host         : {DB_CONFIG['host']}")
print(f"Port         : {DB_CONFIG['port']}")
print(f"Started      : {CURRENT_TIMESTAMP}")

print("\nEnvironment Ready.")

PostgreSQL Username:  postgres
PostgreSQL Password:  ········

================================================================================
ECOMMERCE-AI-PLATFORM
Notebook 14 - AI Business Insights Engine
================================================================================
Project Root : C:\Users\asus\Documents\ECOMMERCE-AI-PLATFORM
Database     : ecommerce_ai_db
Host         : localhost
Port         : 5432
Started      : 2026-07-31 18:01:53.574094

Environment Ready.

In [2]:
def create_psycopg2_connection(config: dict):

    connection = psycopg2.connect(
        host=config["host"],
        port=config["port"],
        dbname=config["database"],
        user=config["user"],
        password=config["password"]
    )

    connection.autocommit = False

    return connection


def create_sqlalchemy_engine(config: dict) -> Engine:

    connection_url = (
        f"postgresql+psycopg2://"
        f"{config['user']}:{config['password']}"
        f"@{config['host']}:{config['port']}"
        f"/{config['database']}"
    )

    engine = create_engine(
        connection_url,
        future=True,
        pool_pre_ping=True
    )

    return engine


try:

    conn = create_psycopg2_connection(DB_CONFIG)
    engine = create_sqlalchemy_engine(DB_CONFIG)

    with engine.connect() as connection:
        connection.execute(text("SELECT 1"))

    print("Database connection successful.")

except Exception as e:

    raise RuntimeError(
        f"Unable to establish PostgreSQL connection.\n{e}"
    )

Database connection successful.

In [3]:
def rollback_transaction(connection):

    try:
        connection.rollback()
    except Exception:
        pass


def execute_query(connection, query, params=None):

    try:

        with connection.cursor() as cursor:

            cursor.execute(query, params)

            if cursor.description is None:
                connection.commit()
                return None

            columns = [column[0] for column in cursor.description]

            rows = cursor.fetchall()

            connection.commit()

            return pd.DataFrame(rows, columns=columns)

    except Exception as error:

        rollback_transaction(connection)

        raise RuntimeError(error)


def dataframe_to_postgresql(
    dataframe: pd.DataFrame,
    table_name: str,
    schema_name: str,
    engine: Engine,
    if_exists: str = "replace"
):

    dataframe.to_sql(
        name=table_name,
        schema=schema_name,
        con=engine,
        index=False,
        if_exists=if_exists,
        method="multi",
        chunksize=5000
    )

In [4]:
DATABASE_DISCOVERY_SQL = """
SELECT
    n.nspname AS schema_name,
    c.relname AS object_name,
    CASE
        WHEN c.relkind='r' THEN 'table'
        WHEN c.relkind='v' THEN 'view'
        WHEN c.relkind='m' THEN 'materialized_view'
        ELSE c.relkind::text
    END AS object_type
FROM pg_class c
JOIN pg_namespace n
ON n.oid=c.relnamespace
WHERE
n.nspname NOT IN
(
'pg_catalog',
'information_schema'
)
ORDER BY
schema_name,
object_type,
object_name;
"""

database_objects = execute_query(
    conn,
    DATABASE_DISCOVERY_SQL
)

if database_objects.empty:
    raise RuntimeError("No accessible database objects were discovered.")

display(database_objects.head(100))

print(f"\nDiscovered Objects : {len(database_objects)}")
print(f"Schemas            : {database_objects['schema_name'].nunique()}")

           schema_name                             object_name object_type
0            analytics                     clv_overall_summary       table
1            analytics                     clv_segment_summary       table
2            analytics                          clv_validation       table
3            analytics            customer_churn_model_metrics       table
4            analytics              customer_churn_predictions       table
5            analytics                 customer_lifetime_value       table
6            analytics                   customer_segmentation       table
7            analytics  customer_segmentation_model_evaluation       table
8            analytics                    segment_distribution       table
9            analytics                   segment_feature_means       table
10           analytics                         segment_summary       table
11  feature_engineered                       category_features       table
12  feature_engineered                       customer_features       table
13  feature_engineered                  monthly_sales_features       table
14  feature_engineered                          order_features       table
15  feature_engineered                        product_features       table
16  feature_engineered                         seller_features       table
17         forecasting                   future_sales_forecast       table
18         forecasting               historical_sales_forecast       table
19         forecasting                        model_evaluation       table
20            pg_toast                     pg_toast_1213_index           i
21            pg_toast                     pg_toast_1247_index           i
22            pg_toast                     pg_toast_1255_index           i
23            pg_toast                     pg_toast_1262_index           i
24            pg_toast                     pg_toast_1417_index           i
25            pg_toast                     pg_toast_1418_index           i
26            pg_toast                    pg_toast_15043_index           i
27            pg_toast                    pg_toast_15048_index           i
28            pg_toast                    pg_toast_15053_index           i
29            pg_toast                    pg_toast_15058_index           i
30            pg_toast                    pg_toast_16389_index           i
31            pg_toast                    pg_toast_16394_index           i
32            pg_toast                    pg_toast_16399_index           i
33            pg_toast                    pg_toast_16404_index           i
34            pg_toast                    pg_toast_16409_index           i
35            pg_toast                    pg_toast_16414_index           i
36            pg_toast                    pg_toast_16419_index           i
37            pg_toast                    pg_toast_16424_index           i
38            pg_toast                    pg_toast_16429_index           i
39            pg_toast                    pg_toast_16481_index           i
40            pg_toast                    pg_toast_16486_index           i
41            pg_toast                    pg_toast_16494_index           i
42            pg_toast                    pg_toast_16499_index           i
43            pg_toast                    pg_toast_16507_index           i
44            pg_toast                    pg_toast_16524_index           i
45            pg_toast                    pg_toast_16529_index           i
46            pg_toast                    pg_toast_16534_index           i
47            pg_toast                    pg_toast_16539_index           i
48            pg_toast                    pg_toast_16545_index           i
49            pg_toast                    pg_toast_16550_index           i
50            pg_toast                    pg_toast_16555_index           i
51            pg_toast                    pg_toast_16560_index           i
52            pg_toast                    pg_toast_16565_index           i
53            pg_toast                    pg_toast_16593_index           i
54            pg_toast                    pg_toast_16598_index           i
55            pg_toast                    pg_toast_16603_index           i
56            pg_toast                    pg_toast_16608_index           i
57            pg_toast                    pg_toast_16614_index           i
58            pg_toast                    pg_toast_16619_index           i
59            pg_toast                    pg_toast_16625_index           i
60            pg_toast                    pg_toast_16630_index           i
61            pg_toast                    pg_toast_16658_index           i
62            pg_toast                    pg_toast_16663_index           i
63            pg_toast                    pg_toast_16668_index           i
64            pg_toast                    pg_toast_16673_index           i
65            pg_toast                    pg_toast_16696_index           i
66            pg_toast                    pg_toast_16701_index           i
67            pg_toast                    pg_toast_16706_index           i
68            pg_toast                     pg_toast_2328_index           i
69            pg_toast                     pg_toast_2396_index           i
70            pg_toast                     pg_toast_2600_index           i
71            pg_toast                     pg_toast_2604_index           i
72            pg_toast                     pg_toast_2606_index           i
73            pg_toast                     pg_toast_2609_index           i
74            pg_toast                     pg_toast_2610_index           i
75            pg_toast                     pg_toast_2612_index           i
76            pg_toast                     pg_toast_2615_index           i
77            pg_toast                     pg_toast_2618_index           i
78            pg_toast                     pg_toast_2619_index           i
79            pg_toast                     pg_toast_2620_index           i
80            pg_toast                     pg_toast_2964_index           i
81            pg_toast                     pg_toast_3079_index           i
82            pg_toast                     pg_toast_3118_index           i
83            pg_toast                     pg_toast_3256_index           i
84            pg_toast                     pg_toast_3350_index           i
85            pg_toast                     pg_toast_3381_index           i
86            pg_toast                     pg_toast_3394_index           i
87            pg_toast                     pg_toast_3429_index           i
88            pg_toast                     pg_toast_3456_index           i
89            pg_toast                     pg_toast_3466_index           i
90            pg_toast                     pg_toast_3592_index           i
91            pg_toast                     pg_toast_3596_index           i
92            pg_toast                     pg_toast_3600_index           i
93            pg_toast                     pg_toast_6100_index           i
94            pg_toast                     pg_toast_6106_index           i
95            pg_toast                     pg_toast_6243_index           i
96            pg_toast                      pg_toast_826_index           i
97            pg_toast                           pg_toast_1213           t
98            pg_toast                           pg_toast_1247           t
99            pg_toast                           pg_toast_1255           t

Discovered Objects : 193
Schemas            : 7

In [5]:
COLUMN_DISCOVERY_SQL = """
SELECT

table_schema,

table_name,

column_name,

ordinal_position,

data_type,

is_nullable

FROM information_schema.columns

WHERE

table_schema NOT IN

(

'pg_catalog',

'information_schema'

)

ORDER BY

table_schema,

table_name,

ordinal_position;
"""

database_columns = execute_query(
    conn,
    COLUMN_DISCOVERY_SQL
)

if database_columns.empty:
    raise RuntimeError("Column discovery failed.")

display(database_columns.head(100))

print(f"Columns discovered : {len(database_columns):,}")

,table_schema,table_name,column_name,ordinal_position,data_type,is_nullable
0,analytics,clv_overall_summary,metric,1,text,YES
1,analytics,clv_overall_summary,value,2,text,YES
2,analytics,clv_segment_summary,clv_segment,1,text,YES
3,analytics,clv_segment_summary,customer_count,2,bigint,YES
4,analytics,clv_segment_summary,total_historical_clv,3,double precision,YES
5,analytics,clv_segment_summary,average_historical_clv,4,double precision,YES
6,analytics,clv_segment_summary,median_historical_clv,5,double precision,YES
7,analytics,clv_segment_summary,minimum_historical_clv,6,double precision,YES
8,analytics,clv_segment_summary,maximum_historical_clv,7,double precision,YES
9,analytics,clv_segment_summary,clv_value_share,8,double precision,YES
10,analytics,clv_segment_summary,customer_share,9,double precision,YES
11,analytics,clv_validation,validation_check,1,text,YES
12,analytics,clv_validation,validation_value,2,text,YES
13,analytics,customer_churn_model_metrics,model,1,text,YES
14,analytics,customer_churn_model_metrics,threshold,2,double precision,YES
15,analytics,customer_churn_model_metrics,accuracy,3,double precision,YES
16,analytics,customer_churn_model_metrics,precision,4,double precision,YES
17,analytics,customer_churn_model_metrics,recall,5,double precision,YES
18,analytics,customer_churn_model_metrics,f1,6,double precision,YES
19,analytics,customer_churn_model_metrics,roc_auc,7,double precision,YES
20,analytics,customer_churn_model_metrics,predicted_churned,8,bigint,YES
21,analytics,customer_churn_model_metrics,predicted_active,9,bigint,YES
22,analytics,customer_churn_model_metrics,predicts_only_one_class,10,boolean,YES
23,analytics,customer_churn_predictions,customer_unique_id,1,text,YES
24,analytics,customer_churn_predictions,churn_probability,2,double precision,YES
25,analytics,customer_churn_predictions,churn_prediction,3,bigint,YES
26,analytics,customer_churn_predictions,churn_status,4,text,YES
27,analytics,customer_churn_predictions,risk_level,5,text,YES
28,analytics,customer_churn_predictions,prediction_cutoff_date,6,timestamp without time zone,YES
29,analytics,customer_churn_predictions,future_horizon_days,7,bigint,YES
30,analytics,customer_churn_predictions,model_name,8,text,YES
31,analytics,customer_churn_predictions,model_threshold,9,double precision,YES
32,analytics,customer_lifetime_value,customer_id,1,text,YES
33,analytics,customer_lifetime_value,historical_customer_value,2,double precision,YES
34,analytics,customer_lifetime_value,customer_lifetime_duration,3,double precision,YES
35,analytics,customer_lifetime_value,historical_clv,4,double precision,YES
36,analytics,customer_lifetime_value,estimated_future_clv,5,double precision,YES
37,analytics,customer_lifetime_value,clv_segment,6,text,YES
38,analytics,customer_segmentation,customer_id,1,text,YES
39,analytics,customer_segmentation,customer_zip_code_prefix,2,double precision,YES
40,analytics,customer_segmentation,total_orders,3,double precision,YES
41,analytics,customer_segmentation,total_spend,4,double precision,YES
42,analytics,customer_segmentation,average_order_value,5,double precision,YES
43,analytics,customer_segmentation,total_items_purchased,6,double precision,YES
44,analytics,customer_segmentation,average_review_score,7,double precision,YES
45,analytics,customer_segmentation,average_delivery_days,8,double precision,YES
46,analytics,customer_segmentation,average_delivery_delay_days,9,double precision,YES
47,analytics,customer_segmentation,late_orders,10,double precision,YES
48,analytics,customer_segmentation,cancelled_orders,11,double precision,YES
49,analytics,customer_segmentation,customer_lifetime_days,12,double precision,YES
50,analytics,customer_segmentation,purchase_frequency,13,double precision,YES
51,analytics,customer_segmentation,recency_days,14,double precision,YES
52,analytics,customer_segmentation,frequency,15,double precision,YES
53,analytics,customer_segmentation,monetary,16,double precision,YES
54,analytics,customer_segmentation,cluster_id,17,bigint,YES
55,analytics,customer_segmentation,segment_name,18,text,YES
56,analytics,customer_segmentation_model_evaluation,k,1,bigint,YES
57,analytics,customer_segmentation_model_evaluation,silhouette_score,2,double precision,YES
58,analytics,customer_segmentation_model_evaluation,evaluation_sample_size,3,bigint,YES
59,analytics,customer_segmentation_model_evaluation,selected_model,4,boolean,YES
60,analytics,customer_segmentation_model_evaluation,feature_count,5,bigint,YES
61,analytics,customer_segmentation_model_evaluation,selected_table,6,text,YES
62,analytics,customer_segmentation_model_evaluation,customer_identifier_column,7,text,YES
63,analytics,segment_distribution,cluster_id,1,bigint,YES
64,analytics,segment_distribution,segment_name,2,text,YES
65,analytics,segment_distribution,customer_count,3,bigint,YES
66,analytics,segment_distribution,customer_percentage,4,double precision,YES
67,analytics,segment_feature_means,cluster_id,1,bigint,YES
68,analytics,segment_feature_means,segment_name,2,text,YES
69,analytics,segment_feature_means,customer_zip_code_prefix,3,double precision,YES
70,analytics,segment_feature_means,total_spend,4,double precision,YES
71,analytics,segment_feature_means,average_order_value,5,double precision,YES
72,analytics,segment_feature_means,total_items_purchased,6,double precision,YES
73,analytics,segment_feature_means,average_review_score,7,double precision,YES
74,analytics,segment_feature_means,average_delivery_days,8,double precision,YES
75,analytics,segment_feature_means,average_delivery_delay_days,9,double precision,YES
76,analytics,segment_feature_means,late_orders,10,double precision,YES
77,analytics,segment_feature_means,cancelled_orders,11,double precision,YES
78,analytics,segment_feature_means,recency_days,12,double precision,YES
79,analytics,segment_feature_means,monetary,13,double precision,YES
80,analytics,segment_summary,cluster_id,1,bigint,YES
81,analytics,segment_summary,mean_customer_zip_code_prefix,2,double precision,YES
82,analytics,segment_summary,median_customer_zip_code_prefix,3,double precision,YES
83,analytics,segment_summary,min_customer_zip_code_prefix,4,double precision,YES
84,analytics,segment_summary,max_customer_zip_code_prefix,5,double precision,YES
85,analytics,segment_summary,mean_total_spend,6,double precision,YES
86,analytics,segment_summary,median_total_spend,7,double precision,YES
87,analytics,segment_summary,min_total_spend,8,double precision,YES
88,analytics,segment_summary,max_total_spend,9,double precision,YES
89,analytics,segment_summary,mean_average_order_value,10,double precision,YES
90,analytics,segment_summary,median_average_order_value,11,double precision,YES
91,analytics,segment_summary,min_average_order_value,12,double precision,YES
92,analytics,segment_summary,max_average_order_value,13,double precision,YES
93,analytics,segment_summary,mean_total_items_purchased,14,double precision,YES
94,analytics,segment_summary,median_total_items_purchased,15,double precision,YES
95,analytics,segment_summary,min_total_items_purchased,16,double precision,YES
96,analytics,segment_summary,max_total_items_purchased,17,double precision,YES
97,analytics,segment_summary,mean_average_review_score,18,double precision,YES
98,analytics,segment_summary,median_average_review_score,19,double precision,YES
99,analytics,segment_summary,min_average_review_score,20,double precision,YES

Columns discovered : 378

In [6]:
PRIMARY_KEY_SQL = """
SELECT

tc.table_schema,
tc.table_name,
kcu.column_name,
kcu.ordinal_position,
tc.constraint_name

FROM information_schema.table_constraints tc

JOIN information_schema.key_column_usage kcu

ON tc.constraint_name = kcu.constraint_name
AND tc.table_schema = kcu.table_schema

WHERE tc.constraint_type='PRIMARY KEY'

ORDER BY

tc.table_schema,
tc.table_name,
kcu.ordinal_position;
"""

primary_keys = execute_query(
    conn,
    PRIMARY_KEY_SQL
)

display(primary_keys)

print(f"Primary Key Columns : {len(primary_keys):,}")

,table_schema,table_name,column_name,ordinal_position,constraint_name
0,pg_catalog,pg_aggregate,aggfnoid,1,pg_aggregate_fnoid_index
1,pg_catalog,pg_am,oid,1,pg_am_oid_index
2,pg_catalog,pg_amop,oid,1,pg_amop_oid_index
3,pg_catalog,pg_amproc,oid,1,pg_amproc_oid_index
4,pg_catalog,pg_attrdef,oid,1,pg_attrdef_oid_index
5,pg_catalog,pg_attribute,attrelid,1,pg_attribute_relid_attnum_index
6,pg_catalog,pg_attribute,attnum,2,pg_attribute_relid_attnum_index
7,pg_catalog,pg_auth_members,oid,1,pg_auth_members_oid_index
8,pg_catalog,pg_authid,oid,1,pg_authid_oid_index
9,pg_catalog,pg_cast,oid,1,pg_cast_oid_index
10,pg_catalog,pg_class,oid,1,pg_class_oid_index
11,pg_catalog,pg_collation,oid,1,pg_collation_oid_index
12,pg_catalog,pg_constraint,oid,1,pg_constraint_oid_index
13,pg_catalog,pg_conversion,oid,1,pg_conversion_oid_index
14,pg_catalog,pg_database,oid,1,pg_database_oid_index
15,pg_catalog,pg_db_role_setting,setdatabase,1,pg_db_role_setting_databaseid_rol_index
16,pg_catalog,pg_db_role_setting,setrole,2,pg_db_role_setting_databaseid_rol_index
17,pg_catalog,pg_default_acl,oid,1,pg_default_acl_oid_index
18,pg_catalog,pg_description,objoid,1,pg_description_o_c_o_index
19,pg_catalog,pg_description,classoid,2,pg_description_o_c_o_index
20,pg_catalog,pg_description,objsubid,3,pg_description_o_c_o_index
21,pg_catalog,pg_enum,oid,1,pg_enum_oid_index
22,pg_catalog,pg_event_trigger,oid,1,pg_event_trigger_oid_index
23,pg_catalog,pg_extension,oid,1,pg_extension_oid_index
24,pg_catalog,pg_foreign_data_wrapper,oid,1,pg_foreign_data_wrapper_oid_index
25,pg_catalog,pg_foreign_server,oid,1,pg_foreign_server_oid_index
26,pg_catalog,pg_foreign_table,ftrelid,1,pg_foreign_table_relid_index
27,pg_catalog,pg_index,indexrelid,1,pg_index_indexrelid_index
28,pg_catalog,pg_inherits,inhrelid,1,pg_inherits_relid_seqno_index
29,pg_catalog,pg_inherits,inhseqno,2,pg_inherits_relid_seqno_index
30,pg_catalog,pg_init_privs,objoid,1,pg_init_privs_o_c_o_index
31,pg_catalog,pg_init_privs,classoid,2,pg_init_privs_o_c_o_index
32,pg_catalog,pg_init_privs,objsubid,3,pg_init_privs_o_c_o_index
33,pg_catalog,pg_language,oid,1,pg_language_oid_index
34,pg_catalog,pg_largeobject,loid,1,pg_largeobject_loid_pn_index
35,pg_catalog,pg_largeobject,pageno,2,pg_largeobject_loid_pn_index
36,pg_catalog,pg_largeobject_metadata,oid,1,pg_largeobject_metadata_oid_index
37,pg_catalog,pg_namespace,oid,1,pg_namespace_oid_index
38,pg_catalog,pg_opclass,oid,1,pg_opclass_oid_index
39,pg_catalog,pg_operator,oid,1,pg_operator_oid_index
40,pg_catalog,pg_opfamily,oid,1,pg_opfamily_oid_index
41,pg_catalog,pg_parameter_acl,oid,1,pg_parameter_acl_oid_index
42,pg_catalog,pg_partitioned_table,partrelid,1,pg_partitioned_table_partrelid_index
43,pg_catalog,pg_policy,oid,1,pg_policy_oid_index
44,pg_catalog,pg_proc,oid,1,pg_proc_oid_index
45,pg_catalog,pg_publication,oid,1,pg_publication_oid_index
46,pg_catalog,pg_publication_namespace,oid,1,pg_publication_namespace_oid_index
47,pg_catalog,pg_publication_rel,oid,1,pg_publication_rel_oid_index
48,pg_catalog,pg_range,rngtypid,1,pg_range_rngtypid_index
49,pg_catalog,pg_replication_origin,roident,1,pg_replication_origin_roiident_index
50,pg_catalog,pg_rewrite,oid,1,pg_rewrite_oid_index
51,pg_catalog,pg_seclabel,objoid,1,pg_seclabel_object_index
52,pg_catalog,pg_seclabel,classoid,2,pg_seclabel_object_index
53,pg_catalog,pg_seclabel,objsubid,3,pg_seclabel_object_index
54,pg_catalog,pg_seclabel,provider,4,pg_seclabel_object_index
55,pg_catalog,pg_sequence,seqrelid,1,pg_sequence_seqrelid_index
56,pg_catalog,pg_shdescription,objoid,1,pg_shdescription_o_c_index
57,pg_catalog,pg_shdescription,classoid,2,pg_shdescription_o_c_index
58,pg_catalog,pg_shseclabel,objoid,1,pg_shseclabel_object_index
59,pg_catalog,pg_shseclabel,classoid,2,pg_shseclabel_object_index
60,pg_catalog,pg_shseclabel,provider,3,pg_shseclabel_object_index
61,pg_catalog,pg_statistic,starelid,1,pg_statistic_relid_att_inh_index
62,pg_catalog,pg_statistic,staattnum,2,pg_statistic_relid_att_inh_index
63,pg_catalog,pg_statistic,stainherit,3,pg_statistic_relid_att_inh_index
64,pg_catalog,pg_statistic_ext,oid,1,pg_statistic_ext_oid_index
65,pg_catalog,pg_statistic_ext_data,stxoid,1,pg_statistic_ext_data_stxoid_inh_index
66,pg_catalog,pg_statistic_ext_data,stxdinherit,2,pg_statistic_ext_data_stxoid_inh_index
67,pg_catalog,pg_subscription,oid,1,pg_subscription_oid_index
68,pg_catalog,pg_subscription_rel,srrelid,1,pg_subscription_rel_srrelid_srsubid_index
69,pg_catalog,pg_subscription_rel,srsubid,2,pg_subscription_rel_srrelid_srsubid_index
70,pg_catalog,pg_tablespace,oid,1,pg_tablespace_oid_index
71,pg_catalog,pg_transform,oid,1,pg_transform_oid_index
72,pg_catalog,pg_trigger,oid,1,pg_trigger_oid_index
73,pg_catalog,pg_ts_config,oid,1,pg_ts_config_oid_index
74,pg_catalog,pg_ts_config_map,mapcfg,1,pg_ts_config_map_index
75,pg_catalog,pg_ts_config_map,maptokentype,2,pg_ts_config_map_index
76,pg_catalog,pg_ts_config_map,mapseqno,3,pg_ts_config_map_index
77,pg_catalog,pg_ts_dict,oid,1,pg_ts_dict_oid_index
78,pg_catalog,pg_ts_parser,oid,1,pg_ts_parser_oid_index
79,pg_catalog,pg_ts_template,oid,1,pg_ts_template_oid_index
80,pg_catalog,pg_type,oid,1,pg_type_oid_index
81,pg_catalog,pg_user_mapping,oid,1,pg_user_mapping_oid_index

Primary Key Columns : 82

In [7]:
FOREIGN_KEY_SQL = """
SELECT

tc.table_schema,

tc.table_name,

kcu.column_name,

ccu.table_schema AS referenced_schema,

ccu.table_name AS referenced_table,

ccu.column_name AS referenced_column,

tc.constraint_name

FROM information_schema.table_constraints tc

JOIN information_schema.key_column_usage kcu

ON tc.constraint_name=kcu.constraint_name

AND tc.table_schema=kcu.table_schema

JOIN information_schema.constraint_column_usage ccu

ON ccu.constraint_name=tc.constraint_name

AND ccu.table_schema=tc.table_schema

WHERE tc.constraint_type='FOREIGN KEY'

ORDER BY

tc.table_schema,

tc.table_name;
"""

foreign_keys = execute_query(
    conn,
    FOREIGN_KEY_SQL
)

display(foreign_keys)

print(f"Foreign Keys : {len(foreign_keys):,}")

Empty DataFrame
Columns: [table_schema, table_name, column_name, referenced_schema, referenced_table, referenced_column, constraint_name]
Index: []

Foreign Keys : 0

In [8]:
row_statistics = []

for _, row in database_objects.iterrows():

    if row["object_type"] != "table":
        continue

    schema_name = row["schema_name"]
    table_name = row["object_name"]

    query = sql.SQL("""
        SELECT COUNT(*) AS row_count
        FROM {}.{}
    """).format(
        sql.Identifier(schema_name),
        sql.Identifier(table_name)
    )

    try:

        result = execute_query(
            conn,
            query.as_string(conn)
        )

        row_statistics.append({
            "schema_name": schema_name,
            "table_name": table_name,
            "row_count": int(result.iloc[0, 0])
        })

    except Exception:

        row_statistics.append({
            "schema_name": schema_name,
            "table_name": table_name,
            "row_count": np.nan
        })

row_statistics = pd.DataFrame(row_statistics)

display(row_statistics)

print(f"Validated Tables : {len(row_statistics)}")

           schema_name                              table_name  row_count
0            analytics                     clv_overall_summary          9
1            analytics                     clv_segment_summary          3
2            analytics                          clv_validation          9
3            analytics            customer_churn_model_metrics          1
4            analytics              customer_churn_predictions      86924
5            analytics                 customer_lifetime_value      99441
6            analytics                   customer_segmentation      99441
7            analytics  customer_segmentation_model_evaluation          7
8            analytics                    segment_distribution          2
9            analytics                   segment_feature_means          2
10           analytics                         segment_summary          2
11  feature_engineered                       category_features         74
12  feature_engineered                       customer_features      99441
13  feature_engineered                  monthly_sales_features         25
14  feature_engineered                          order_features      99441
15  feature_engineered                        product_features      32951
16  feature_engineered                         seller_features       3095
17         forecasting                   future_sales_forecast         30
18         forecasting               historical_sales_forecast       1299
19         forecasting                        model_evaluation          2
20              public                    category_translation         71
21              public                  churn_model_comparison          2
22              public              customer_churn_predictions      99441
23              public                               customers      99441
24              public                             geolocation     738332
25              public                             order_items     112650
26              public                          order_payments     103886
27              public                           order_reviews      99224
28              public                                  orders      99441
29              public                                products      32951
30              public                                 sellers       3095
31     recommendations         powerbi_product_recommendations     986670
32     recommendations                 product_recommendations     986670
33     recommendations             recommendation_data_quality          8
34     recommendations               recommendation_evaluation          1
35     sales_analytics                    delivery_performance          2
36     sales_analytics                           monthly_sales         25
37     sales_analytics                    order_status_summary          8
38     sales_analytics                      overall_sales_kpis          1

Validated Tables : 39

In [9]:
table_validation = []

for _, table in row_statistics.iterrows():

    schema_name = table["schema_name"]
    table_name = table["table_name"]

    columns = database_columns[
        (database_columns.table_schema == schema_name)
        &
        (database_columns.table_name == table_name)
    ]

    duplicate_columns = columns.column_name.duplicated().sum()

    table_validation.append({

        "schema_name": schema_name,

        "table_name": table_name,

        "row_count": table["row_count"],

        "column_count": len(columns),

        "duplicate_column_names": duplicate_columns,

        "nullable_columns":

        int(
            (
                columns["is_nullable"] == "YES"
            ).sum()
        )

    })

table_validation = pd.DataFrame(table_validation)

display(table_validation)

,schema_name,table_name,row_count,column_count,duplicate_column_names,nullable_columns
0,analytics,clv_overall_summary,9,2,0,2
1,analytics,clv_segment_summary,3,9,0,9
2,analytics,clv_validation,9,2,0,2
3,analytics,customer_churn_model_metrics,1,10,0,10
4,analytics,customer_churn_predictions,86924,9,0,9
5,analytics,customer_lifetime_value,99441,6,0,6
6,analytics,customer_segmentation,99441,18,0,18
7,analytics,customer_segmentation_model_evaluation,7,7,0,7
8,analytics,segment_distribution,2,4,0,4
9,analytics,segment_feature_means,2,13,0,13
10,analytics,segment_summary,2,48,0,48
11,feature_engineered,category_features,74,5,0,5
12,feature_engineered,customer_features,99441,25,0,25
13,feature_engineered,monthly_sales_features,25,11,0,11
14,feature_engineered,order_features,99441,35,0,35
15,feature_engineered,product_features,32951,18,0,18
16,feature_engineered,seller_features,3095,10,0,10
17,forecasting,future_sales_forecast,30,5,0,5
18,forecasting,historical_sales_forecast,1299,6,0,6
19,forecasting,model_evaluation,2,5,0,5
20,public,category_translation,71,2,0,2
21,public,churn_model_comparison,2,6,0,6
22,public,customer_churn_predictions,99441,10,0,10
23,public,customers,99441,5,0,5
24,public,geolocation,738332,5,0,5
25,public,order_items,112650,7,0,7
26,public,order_payments,103886,5,0,5
27,public,order_reviews,99224,7,0,7
28,public,orders,99441,16,0,16
29,public,products,32951,10,0,10
30,public,sellers,3095,4,0,4
31,recommendations,powerbi_product_recommendations,986670,13,0,13
32,recommendations,product_recommendations,986670,7,0,7
33,recommendations,recommendation_data_quality,8,3,0,3
34,recommendations,recommendation_evaluation,1,6,0,6
35,sales_analytics,delivery_performance,2,3,0,3
36,sales_analytics,monthly_sales,25,6,0,6
37,sales_analytics,order_status_summary,8,2,0,2
38,sales_analytics,overall_sales_kpis,1,13,0,13

In [10]:
NOTEBOOK_OUTPUT_PATTERNS = {

    "sales_analytics": [

        "sales",
        "analytics",
        "revenue",
        "monthly_sales"

    ],

    "customer_segmentation": [

        "segment",
        "cluster"

    ],

    "customer_lifetime_value": [

        "clv",
        "lifetime"

    ],

    "customer_churn": [

        "churn"

    ],

    "recommendation": [

        "recommend",

        "recommendation"

    ],

    "forecast": [

        "forecast",

        "prediction",

        "future"

    ],

    "feature_engineering": [

        "feature"

    ]

}

validated_outputs = {}

for notebook_name, keywords in NOTEBOOK_OUTPUT_PATTERNS.items():

    discovered = []

    for _, obj in database_objects.iterrows():

        object_name = obj["object_name"].lower()

        if any(keyword in object_name for keyword in keywords):

            discovered.append({

                "schema": obj["schema_name"],

                "table": obj["object_name"],

                "type": obj["object_type"]

            })

    validated_outputs[notebook_name] = pd.DataFrame(discovered)

for notebook_name, dataframe in validated_outputs.items():

    print("\n" + "=" * 70)

    print(notebook_name.upper())

    print("=" * 70)

    if dataframe.empty:

        print("No validated outputs discovered.")

    else:

        display(dataframe)

======================================================================
SALES_ANALYTICS
======================================================================

               schema                      table   type
0  feature_engineered     monthly_sales_features  table
1         forecasting      future_sales_forecast  table
2         forecasting  historical_sales_forecast  table
3     sales_analytics              monthly_sales  table
4     sales_analytics         overall_sales_kpis  table

======================================================================
CUSTOMER_SEGMENTATION
======================================================================

      schema                                   table   type
0  analytics                     clv_segment_summary  table
1  analytics                   customer_segmentation  table
2  analytics  customer_segmentation_model_evaluation  table
3  analytics                    segment_distribution  table
4  analytics                   segment_feature_means  table
5  analytics                         segment_summary  table

======================================================================
CUSTOMER_LIFETIME_VALUE
======================================================================

      schema                    table   type
0  analytics      clv_overall_summary  table
1  analytics      clv_segment_summary  table
2  analytics           clv_validation  table
3  analytics  customer_lifetime_value  table

======================================================================
CUSTOMER_CHURN
======================================================================

      schema                         table   type
0  analytics  customer_churn_model_metrics  table
1  analytics    customer_churn_predictions  table
2     public        churn_model_comparison  table
3     public    customer_churn_predictions  table

======================================================================
RECOMMENDATION
======================================================================

            schema                            table   type
0  recommendations  powerbi_product_recommendations  table
1  recommendations          product_recommendations  table
2  recommendations      recommendation_data_quality  table
3  recommendations        recommendation_evaluation  table

======================================================================
FORECAST
======================================================================

        schema                       table   type
0    analytics  customer_churn_predictions  table
1  forecasting       future_sales_forecast  table
2  forecasting   historical_sales_forecast  table
3       public  customer_churn_predictions  table

======================================================================
FEATURE_ENGINEERING
======================================================================

               schema                   table   type
0           analytics   segment_feature_means  table
1  feature_engineered       category_features  table
2  feature_engineered       customer_features  table
3  feature_engineered  monthly_sales_features  table
4  feature_engineered          order_features  table
5  feature_engineered        product_features  table
6  feature_engineered         seller_features  table

In [11]:
validated_tables = {}

for notebook_name, discovery_df in validated_outputs.items():

    notebook_tables = {}

    if discovery_df.empty:

        validated_tables[notebook_name] = notebook_tables

        continue

    for _, table in discovery_df.iterrows():

        schema_name = table["schema"]
        table_name = table["table"]

        query = sql.SQL("""

            SELECT *

            FROM {}.{}

            LIMIT 50000

        """).format(

            sql.Identifier(schema_name),

            sql.Identifier(table_name)

        )

        try:

            dataframe = execute_query(
                conn,
                query.as_string(conn)
            )

            notebook_tables[f"{schema_name}.{table_name}"] = dataframe

        except Exception:

            continue

    validated_tables[notebook_name] = notebook_tables

print("Validated notebook outputs loaded successfully.")

Validated notebook outputs loaded successfully.

In [12]:
data_quality_summary = []

for notebook_name, tables in validated_tables.items():

    for table_name, dataframe in tables.items():

        quality = {

            "notebook": notebook_name,

            "table": table_name,

            "rows": len(dataframe),

            "columns": len(dataframe.columns),

            "duplicate_rows": int(dataframe.duplicated().sum()),

            "missing_cells": int(dataframe.isna().sum().sum()),

            "missing_percentage":

            round(

                dataframe.isna().sum().sum()

                /

                max(dataframe.size, 1)

                *

                100,

                2

            )

        }

        data_quality_summary.append(quality)

data_quality_summary = pd.DataFrame(data_quality_summary)

display(data_quality_summary.sort_values(
    "missing_percentage",
    ascending=False
))

,notebook,table,rows,columns,duplicate_rows,missing_cells,missing_percentage
22,recommendation,recommendations.recommendation_evaluation,1,6,0,4,66.67
14,customer_lifetime_value,analytics.customer_lifetime_value,50000,6,0,50000,16.67
0,sales_analytics,feature_engineered.monthly_sales_features,25,11,0,0,0.00
25,forecast,forecasting.historical_sales_forecast,1299,6,0,0,0.00
20,recommendation,recommendations.product_recommendations,50000,7,0,0,0.00
21,recommendation,recommendations.recommendation_data_quality,8,3,0,0,0.00
23,forecast,analytics.customer_churn_predictions,50000,9,0,0,0.00
24,forecast,forecasting.future_sales_forecast,30,5,0,0,0.00
26,forecast,public.customer_churn_predictions,50000,10,0,0,0.00
18,customer_churn,public.customer_churn_predictions,50000,10,0,0,0.00
27,feature_engineering,analytics.segment_feature_means,2,13,0,0,0.00
28,feature_engineering,feature_engineered.category_features,74,5,0,0,0.00
29,feature_engineering,feature_engineered.customer_features,50000,25,0,0,0.00
30,feature_engineering,feature_engineered.monthly_sales_features,25,11,0,0,0.00
31,feature_engineering,feature_engineered.order_features,50000,35,0,0,0.00
32,feature_engineering,feature_engineered.product_features,32951,18,0,0,0.00
19,recommendation,recommendations.powerbi_product_recommendations,50000,13,0,0,0.00
17,customer_churn,public.churn_model_comparison,2,6,0,0,0.00
1,sales_analytics,forecasting.future_sales_forecast,30,5,0,0,0.00
16,customer_churn,analytics.customer_churn_predictions,50000,9,0,0,0.00
15,customer_churn,analytics.customer_churn_model_metrics,1,10,0,0,0.00
13,customer_lifetime_value,analytics.clv_validation,9,2,0,0,0.00
12,customer_lifetime_value,analytics.clv_segment_summary,3,9,0,0,0.00
11,customer_lifetime_value,analytics.clv_overall_summary,9,2,0,0,0.00
10,customer_segmentation,analytics.segment_summary,2,48,0,0,0.00
9,customer_segmentation,analytics.segment_feature_means,2,13,0,0,0.00
8,customer_segmentation,analytics.segment_distribution,2,4,0,0,0.00
7,customer_segmentation,analytics.customer_segmentation_model_evaluation,7,7,0,0,0.00
6,customer_segmentation,analytics.customer_segmentation,50000,18,0,0,0.00
5,customer_segmentation,analytics.clv_segment_summary,3,9,0,0,0.00
4,sales_analytics,sales_analytics.overall_sales_kpis,1,13,0,0,0.00
3,sales_analytics,sales_analytics.monthly_sales,25,6,0,0,0.00
2,sales_analytics,forecasting.historical_sales_forecast,1299,6,0,0,0.00
33,feature_engineering,feature_engineered.seller_features,3095,10,0,0,0.00

In [13]:
all_validated_tables = {}

for notebook_tables in validated_tables.values():

    all_validated_tables.update(notebook_tables)

print(f"Available validated datasets : {len(all_validated_tables)}")

for name in sorted(all_validated_tables):

    print(name)

Available validated datasets : 27
analytics.clv_overall_summary
analytics.clv_segment_summary
analytics.clv_validation
analytics.customer_churn_model_metrics
analytics.customer_churn_predictions
analytics.customer_lifetime_value
analytics.customer_segmentation
analytics.customer_segmentation_model_evaluation
analytics.segment_distribution
analytics.segment_feature_means
analytics.segment_summary
feature_engineered.category_features
feature_engineered.customer_features
feature_engineered.monthly_sales_features
feature_engineered.order_features
feature_engineered.product_features
feature_engineered.seller_features
forecasting.future_sales_forecast
forecasting.historical_sales_forecast
public.churn_model_comparison
public.customer_churn_predictions
recommendations.powerbi_product_recommendations
recommendations.product_recommendations
recommendations.recommendation_data_quality
recommendations.recommendation_evaluation
sales_analytics.monthly_sales
sales_analytics.overall_sales_kpis

In [14]:
def normalize_identifier(name: str) -> str:
    return (
        str(name)
        .strip()
        .lower()
        .replace("-", "_")
        .replace(" ", "_")
    )


COMMON_IDENTIFIER_PRIORITY = [
    "customer_id",
    "order_id",
    "product_id",
    "seller_id",
    "review_id",
    "payment_id",
    "order_item_id",
    "forecast_date",
    "date",
    "month",
    "year"
]

table_identifier_map = {}

for table_name, dataframe in all_validated_tables.items():

    normalized_columns = {
        normalize_identifier(column): column
        for column in dataframe.columns
    }

    discovered_identifiers = []

    for identifier in COMMON_IDENTIFIER_PRIORITY:

        if identifier in normalized_columns:
            discovered_identifiers.append(
                normalized_columns[identifier]
            )

    table_identifier_map[table_name] = discovered_identifiers

identifier_summary = pd.DataFrame(
    [
        {
            "table": table,
            "identifier_columns": identifiers
        }
        for table, identifiers in table_identifier_map.items()
    ]
)

display(identifier_summary)

                                               table       identifier_columns
0          feature_engineered.monthly_sales_features                       []
1                  forecasting.future_sales_forecast                       []
2              forecasting.historical_sales_forecast                       []
3                      sales_analytics.monthly_sales                       []
4                 sales_analytics.overall_sales_kpis                       []
5                      analytics.clv_segment_summary                       []
6                    analytics.customer_segmentation            [customer_id]
7   analytics.customer_segmentation_model_evaluation                       []
8                     analytics.segment_distribution                       []
9                    analytics.segment_feature_means                       []
10                         analytics.segment_summary                       []
11                     analytics.clv_overall_summary                       []
12                          analytics.clv_validation                       []
13                 analytics.customer_lifetime_value            [customer_id]
14            analytics.customer_churn_model_metrics                       []
15              analytics.customer_churn_predictions                       []
16                     public.churn_model_comparison                       []
17                 public.customer_churn_predictions                       []
18   recommendations.powerbi_product_recommendations            [customer_id]
19           recommendations.product_recommendations            [customer_id]
20       recommendations.recommendation_data_quality                       []
21         recommendations.recommendation_evaluation                       []
22              feature_engineered.category_features                       []
23              feature_engineered.customer_features            [customer_id]
24                 feature_engineered.order_features  [customer_id, order_id]
25               feature_engineered.product_features             [product_id]
26                feature_engineered.seller_features              [seller_id]

In [21]:
def normalize_identifier(column_name: str) -> str:
    return (
        str(column_name)
        .strip()
        .lower()
        .replace("-", "_")
        .replace(" ", "_")
    )


COMMON_IDENTIFIER_PRIORITY = [
    "customer_id",
    "order_id",
    "product_id",
    "seller_id",
    "review_id",
    "payment_id",
    "order_item_id",
    "forecast_date",
    "date",
    "month",
    "year"
]


candidate_relationships = []

table_column_lookup = {}

for table_name, dataframe in all_validated_tables.items():

    normalized = {
        normalize_identifier(column): column
        for column in dataframe.columns
    }

    table_column_lookup[table_name] = normalized

table_names = list(all_validated_tables.keys())

for left_index in range(len(table_names)):

    for right_index in range(left_index + 1, len(table_names)):

        left_table = table_names[left_index]
        right_table = table_names[right_index]

        left_columns = table_column_lookup[left_table]
        right_columns = table_column_lookup[right_table]

        common_columns = sorted(
            set(left_columns.keys())
            &
            set(right_columns.keys())
        )

        if not common_columns:
            continue

        prioritized = [
            column
            for column in COMMON_IDENTIFIER_PRIORITY
            if column in common_columns
        ]

        if prioritized:
            common_columns = prioritized

        candidate_relationships.append({

            "left_table": left_table,

            "right_table": right_table,

            "candidate_columns": common_columns

        })

relationship_candidates = pd.DataFrame(candidate_relationships)

display(relationship_candidates)

,left_table,right_table,candidate_columns
0,feature_engineered.monthly_sales_features,sales_analytics.monthly_sales,"[average_order_value, total_orders]"
1,feature_engineered.monthly_sales_features,sales_analytics.overall_sales_kpis,"[average_delivery_days, average_order_value, average_review_score, cancelled_orders, total_orders]"
2,feature_engineered.monthly_sales_features,analytics.customer_segmentation,"[average_delivery_days, average_order_value, average_review_score, cancelled_orders, late_orders, total_orders]"
3,feature_engineered.monthly_sales_features,analytics.segment_feature_means,"[average_delivery_days, average_order_value, average_review_score, cancelled_orders, late_orders]"
4,feature_engineered.monthly_sales_features,feature_engineered.category_features,[total_revenue]
5,feature_engineered.monthly_sales_features,feature_engineered.customer_features,"[average_delivery_days, average_order_value, average_review_score, cancelled_orders, late_orders, total_orders]"
6,feature_engineered.monthly_sales_features,feature_engineered.order_features,[purchase_month_start]
7,feature_engineered.monthly_sales_features,feature_engineered.product_features,[total_revenue]
8,feature_engineered.monthly_sales_features,feature_engineered.seller_features,"[total_items_sold, total_revenue]"
9,forecasting.future_sales_forecast,forecasting.historical_sales_forecast,"[forecast_frequency, forecast_period, forecast_type, model_name]"
10,forecasting.future_sales_forecast,analytics.customer_churn_predictions,[model_name]
11,forecasting.historical_sales_forecast,analytics.customer_churn_predictions,[model_name]
12,sales_analytics.monthly_sales,sales_analytics.overall_sales_kpis,"[average_order_value, total_freight_value, total_order_value, total_orders, total_product_value]"
13,sales_analytics.monthly_sales,analytics.customer_segmentation,"[average_order_value, total_orders]"
14,sales_analytics.monthly_sales,analytics.segment_feature_means,[average_order_value]
15,sales_analytics.monthly_sales,feature_engineered.customer_features,"[average_order_value, total_orders]"
16,sales_analytics.monthly_sales,feature_engineered.order_features,"[total_freight_value, total_order_value, total_product_value]"
17,sales_analytics.monthly_sales,feature_engineered.product_features,[total_freight_value]
18,sales_analytics.monthly_sales,feature_engineered.seller_features,[total_freight_value]
19,sales_analytics.overall_sales_kpis,analytics.customer_segmentation,"[average_delivery_days, average_order_value, average_review_score, cancelled_orders, total_orders]"
20,sales_analytics.overall_sales_kpis,analytics.segment_feature_means,"[average_delivery_days, average_order_value, average_review_score, cancelled_orders]"
21,sales_analytics.overall_sales_kpis,feature_engineered.customer_features,"[average_delivery_days, average_order_value, average_review_score, cancelled_orders, total_orders]"
22,sales_analytics.overall_sales_kpis,feature_engineered.order_features,"[total_freight_value, total_items, total_order_value, total_product_value]"
23,sales_analytics.overall_sales_kpis,feature_engineered.product_features,[total_freight_value]
24,sales_analytics.overall_sales_kpis,feature_engineered.seller_features,[total_freight_value]
25,analytics.clv_segment_summary,analytics.segment_distribution,[customer_count]
26,analytics.clv_segment_summary,analytics.segment_summary,[customer_count]
27,analytics.clv_segment_summary,analytics.customer_lifetime_value,[clv_segment]
28,analytics.customer_segmentation,analytics.segment_distribution,"[cluster_id, segment_name]"
29,analytics.customer_segmentation,analytics.segment_feature_means,"[average_delivery_days, average_delivery_delay_days, average_order_value, average_review_score, cancelled_orders, cluster_id, customer_zip_code_prefix, late_orders, monetary, recency_days, segment_name, total_items_purchased, total_spend]"
30,analytics.customer_segmentation,analytics.segment_summary,"[cluster_id, segment_name]"
31,analytics.customer_segmentation,analytics.customer_lifetime_value,[customer_id]
32,analytics.customer_segmentation,public.customer_churn_predictions,[recency_days]
33,analytics.customer_segmentation,recommendations.powerbi_product_recommendations,[customer_id]
34,analytics.customer_segmentation,recommendations.product_recommendations,[customer_id]
35,analytics.customer_segmentation,feature_engineered.customer_features,[customer_id]
36,analytics.customer_segmentation,feature_engineered.order_features,[customer_id]
37,analytics.segment_distribution,analytics.segment_feature_means,"[cluster_id, segment_name]"
38,analytics.segment_distribution,analytics.segment_summary,"[cluster_id, customer_count, segment_name]"
39,analytics.segment_feature_means,analytics.segment_summary,"[cluster_id, segment_name]"
40,analytics.segment_feature_means,public.customer_churn_predictions,[recency_days]
41,analytics.segment_feature_means,feature_engineered.customer_features,"[average_delivery_days, average_delivery_delay_days, average_order_value, average_review_score, cancelled_orders, customer_zip_code_prefix, late_orders, monetary, recency_days, total_items_purchased, total_spend]"
42,analytics.clv_overall_summary,recommendations.recommendation_data_quality,[value]
43,analytics.customer_lifetime_value,recommendations.powerbi_product_recommendations,[customer_id]
44,analytics.customer_lifetime_value,recommendations.product_recommendations,[customer_id]
45,analytics.customer_lifetime_value,feature_engineered.customer_features,[customer_id]
46,analytics.customer_lifetime_value,feature_engineered.order_features,[customer_id]
47,analytics.customer_churn_model_metrics,public.churn_model_comparison,"[accuracy, model, precision, recall, roc_auc]"
48,analytics.customer_churn_predictions,public.customer_churn_predictions,"[churn_prediction, churn_probability, risk_level]"
49,analytics.customer_churn_predictions,feature_engineered.customer_features,[customer_unique_id]
50,public.customer_churn_predictions,feature_engineered.customer_features,[recency_days]
51,recommendations.powerbi_product_recommendations,recommendations.product_recommendations,[customer_id]
52,recommendations.powerbi_product_recommendations,feature_engineered.customer_features,[customer_id]
53,recommendations.powerbi_product_recommendations,feature_engineered.order_features,[customer_id]
54,recommendations.product_recommendations,feature_engineered.customer_features,[customer_id]
55,recommendations.product_recommendations,feature_engineered.order_features,[customer_id]
56,feature_engineered.category_features,feature_engineered.product_features,"[product_category_name, total_revenue, total_units_sold]"
57,feature_engineered.category_features,feature_engineered.seller_features,[total_revenue]
58,feature_engineered.customer_features,feature_engineered.order_features,[customer_id]
59,feature_engineered.order_features,feature_engineered.product_features,[total_freight_value]
60,feature_engineered.order_features,feature_engineered.seller_features,[total_freight_value]
61,feature_engineered.product_features,feature_engineered.seller_features,"[total_freight_value, total_revenue, unique_orders]"

In [22]:
validated_relationships = []

for _, relationship in relationship_candidates.iterrows():

    left_table = relationship["left_table"]
    right_table = relationship["right_table"]

    left_df = all_validated_tables[left_table]
    right_df = all_validated_tables[right_table]

    for normalized_column in relationship["candidate_columns"]:

        left_column = table_column_lookup[left_table][normalized_column]
        right_column = table_column_lookup[right_table][normalized_column]

        left_series = left_df[left_column].dropna()
        right_series = right_df[right_column].dropna()

        if left_series.empty or right_series.empty:
            continue

        shared_values = len(
            set(left_series.unique())
            &
            set(right_series.unique())
        )

        if shared_values == 0:
            continue

        left_unique = left_series.nunique()
        right_unique = right_series.nunique()

        left_duplicate_ratio = (
            len(left_series) /
            max(left_unique, 1)
        )

        right_duplicate_ratio = (
            len(right_series) /
            max(right_unique, 1)
        )

        if left_duplicate_ratio <= 1.05 and right_duplicate_ratio <= 1.05:
            cardinality = "1:1"

        elif left_duplicate_ratio <= 1.05:
            cardinality = "1:M"

        elif right_duplicate_ratio <= 1.05:
            cardinality = "M:1"

        else:
            cardinality = "M:M"

        validated_relationships.append({

            "left_table": left_table,

            "right_table": right_table,

            "left_column": left_column,

            "right_column": right_column,

            "shared_values": shared_values,

            "cardinality": cardinality

        })

validated_relationships = pd.DataFrame(validated_relationships)

display(validated_relationships)

,left_table,right_table,left_column,right_column,shared_values,cardinality
0,feature_engineered.monthly_sales_features,sales_analytics.monthly_sales,average_order_value,average_order_value,1,1:1
1,feature_engineered.monthly_sales_features,sales_analytics.monthly_sales,total_orders,total_orders,24,1:1
2,feature_engineered.monthly_sales_features,analytics.customer_segmentation,average_delivery_days,average_delivery_days,1,1:1
3,feature_engineered.monthly_sales_features,analytics.customer_segmentation,average_order_value,average_order_value,4,1:M
4,feature_engineered.monthly_sales_features,analytics.customer_segmentation,average_review_score,average_review_score,2,1:M
5,feature_engineered.monthly_sales_features,analytics.customer_segmentation,cancelled_orders,cancelled_orders,1,M:M
6,feature_engineered.monthly_sales_features,analytics.customer_segmentation,late_orders,late_orders,2,M:M
7,feature_engineered.monthly_sales_features,analytics.customer_segmentation,total_orders,total_orders,1,1:M
8,feature_engineered.monthly_sales_features,analytics.segment_feature_means,late_orders,late_orders,1,M:1
9,feature_engineered.monthly_sales_features,feature_engineered.customer_features,average_delivery_days,average_delivery_days,1,1:1
10,feature_engineered.monthly_sales_features,feature_engineered.customer_features,average_order_value,average_order_value,4,1:M
11,feature_engineered.monthly_sales_features,feature_engineered.customer_features,average_review_score,average_review_score,2,1:M
12,feature_engineered.monthly_sales_features,feature_engineered.customer_features,cancelled_orders,cancelled_orders,1,M:M
13,feature_engineered.monthly_sales_features,feature_engineered.customer_features,late_orders,late_orders,2,M:M
14,feature_engineered.monthly_sales_features,feature_engineered.customer_features,total_orders,total_orders,1,1:M
15,feature_engineered.monthly_sales_features,feature_engineered.order_features,purchase_month_start,purchase_month_start,25,1:M
16,feature_engineered.monthly_sales_features,feature_engineered.product_features,total_revenue,total_revenue,1,1:M
17,feature_engineered.monthly_sales_features,feature_engineered.seller_features,total_items_sold,total_items_sold,3,1:M
18,forecasting.future_sales_forecast,forecasting.historical_sales_forecast,forecast_frequency,forecast_frequency,1,M:M
19,forecasting.future_sales_forecast,forecasting.historical_sales_forecast,model_name,model_name,1,M:M
20,sales_analytics.monthly_sales,analytics.customer_segmentation,average_order_value,average_order_value,1,1:M
21,sales_analytics.monthly_sales,analytics.customer_segmentation,total_orders,total_orders,1,1:M
22,sales_analytics.monthly_sales,feature_engineered.customer_features,average_order_value,average_order_value,1,1:M
23,sales_analytics.monthly_sales,feature_engineered.customer_features,total_orders,total_orders,1,1:M
24,sales_analytics.monthly_sales,feature_engineered.order_features,total_freight_value,total_freight_value,1,1:M
25,sales_analytics.monthly_sales,feature_engineered.order_features,total_order_value,total_order_value,1,1:M
26,sales_analytics.monthly_sales,feature_engineered.order_features,total_product_value,total_product_value,2,1:M
27,analytics.clv_segment_summary,analytics.customer_lifetime_value,clv_segment,clv_segment,3,1:M
28,analytics.customer_segmentation,analytics.segment_distribution,cluster_id,cluster_id,2,M:1
29,analytics.customer_segmentation,analytics.segment_distribution,segment_name,segment_name,2,M:1
30,analytics.customer_segmentation,analytics.segment_feature_means,cluster_id,cluster_id,2,M:1
31,analytics.customer_segmentation,analytics.segment_feature_means,late_orders,late_orders,1,M:1
32,analytics.customer_segmentation,analytics.segment_feature_means,segment_name,segment_name,2,M:1
33,analytics.customer_segmentation,analytics.segment_summary,cluster_id,cluster_id,2,M:1
34,analytics.customer_segmentation,analytics.segment_summary,segment_name,segment_name,2,M:1
35,analytics.customer_segmentation,analytics.customer_lifetime_value,customer_id,customer_id,50000,1:1
36,analytics.customer_segmentation,feature_engineered.customer_features,customer_id,customer_id,25203,1:1
37,analytics.customer_segmentation,feature_engineered.order_features,customer_id,customer_id,25222,1:1
38,analytics.segment_distribution,analytics.segment_feature_means,cluster_id,cluster_id,2,1:1
39,analytics.segment_distribution,analytics.segment_feature_means,segment_name,segment_name,2,1:1
40,analytics.segment_distribution,analytics.segment_summary,cluster_id,cluster_id,2,1:1
41,analytics.segment_distribution,analytics.segment_summary,customer_count,customer_count,2,1:1
42,analytics.segment_distribution,analytics.segment_summary,segment_name,segment_name,2,1:1
43,analytics.segment_feature_means,analytics.segment_summary,cluster_id,cluster_id,2,1:1
44,analytics.segment_feature_means,analytics.segment_summary,segment_name,segment_name,2,1:1
45,analytics.segment_feature_means,feature_engineered.customer_features,late_orders,late_orders,1,1:M
46,analytics.customer_lifetime_value,feature_engineered.customer_features,customer_id,customer_id,25203,1:1
47,analytics.customer_lifetime_value,feature_engineered.order_features,customer_id,customer_id,25222,1:1
48,analytics.customer_churn_model_metrics,public.churn_model_comparison,model,model,1,1:1
49,analytics.customer_churn_predictions,feature_engineered.customer_features,customer_unique_id,customer_unique_id,25121,1:1
50,public.customer_churn_predictions,feature_engineered.customer_features,recency_days,recency_days,1,M:1
51,recommendations.powerbi_product_recommendations,recommendations.product_recommendations,customer_id,customer_id,5000,M:M
52,feature_engineered.category_features,feature_engineered.product_features,product_category_name,product_category_name,74,1:M
53,feature_engineered.category_features,feature_engineered.product_features,total_revenue,total_revenue,2,1:M
54,feature_engineered.category_features,feature_engineered.product_features,total_units_sold,total_units_sold,20,M:M
55,feature_engineered.category_features,feature_engineered.seller_features,total_revenue,total_revenue,1,1:M
56,feature_engineered.customer_features,feature_engineered.order_features,customer_id,customer_id,25318,1:1
57,feature_engineered.order_features,feature_engineered.product_features,total_freight_value,total_freight_value,4936,M:M
58,feature_engineered.order_features,feature_engineered.seller_features,total_freight_value,total_freight_value,758,M:M
59,feature_engineered.product_features,feature_engineered.seller_features,total_freight_value,total_freight_value,1081,M:M
60,feature_engineered.product_features,feature_engineered.seller_features,total_revenue,total_revenue,891,M:M
61,feature_engineered.product_features,feature_engineered.seller_features,unique_orders,unique_orders,109,M:M

In [23]:
safe_relationships = validated_relationships[
    validated_relationships["cardinality"] != "M:M"
].copy()

unsafe_relationships = validated_relationships[
    validated_relationships["cardinality"] == "M:M"
].copy()

print(f"Safe Relationships   : {len(safe_relationships)}")
print(f"Unsafe Relationships : {len(unsafe_relationships)}")

if not unsafe_relationships.empty:

    display(unsafe_relationships)

relationship_report = []

for _, row in safe_relationships.iterrows():

    left_df = all_validated_tables[row["left_table"]]
    right_df = all_validated_tables[row["right_table"]]

    left_values = set(
        left_df[row["left_column"]].dropna().unique()
    )

    right_values = set(
        right_df[row["right_column"]].dropna().unique()
    )

    relationship_report.append({

        "left_table": row["left_table"],

        "right_table": row["right_table"],

        "join_column": row["left_column"],

        "matched_keys": len(left_values & right_values),

        "left_unmatched": len(left_values - right_values),

        "right_unmatched": len(right_values - left_values)

    })

relationship_report = pd.DataFrame(relationship_report)

display(relationship_report)

Safe Relationships   : 49
Unsafe Relationships : 13

,left_table,right_table,left_column,right_column,shared_values,cardinality
5,feature_engineered.monthly_sales_features,analytics.customer_segmentation,cancelled_orders,cancelled_orders,1,M:M
6,feature_engineered.monthly_sales_features,analytics.customer_segmentation,late_orders,late_orders,2,M:M
12,feature_engineered.monthly_sales_features,feature_engineered.customer_features,cancelled_orders,cancelled_orders,1,M:M
13,feature_engineered.monthly_sales_features,feature_engineered.customer_features,late_orders,late_orders,2,M:M
18,forecasting.future_sales_forecast,forecasting.historical_sales_forecast,forecast_frequency,forecast_frequency,1,M:M
19,forecasting.future_sales_forecast,forecasting.historical_sales_forecast,model_name,model_name,1,M:M
51,recommendations.powerbi_product_recommendations,recommendations.product_recommendations,customer_id,customer_id,5000,M:M
54,feature_engineered.category_features,feature_engineered.product_features,total_units_sold,total_units_sold,20,M:M
57,feature_engineered.order_features,feature_engineered.product_features,total_freight_value,total_freight_value,4936,M:M
58,feature_engineered.order_features,feature_engineered.seller_features,total_freight_value,total_freight_value,758,M:M
59,feature_engineered.product_features,feature_engineered.seller_features,total_freight_value,total_freight_value,1081,M:M
60,feature_engineered.product_features,feature_engineered.seller_features,total_revenue,total_revenue,891,M:M
61,feature_engineered.product_features,feature_engineered.seller_features,unique_orders,unique_orders,109,M:M

,left_table,right_table,join_column,matched_keys,left_unmatched,right_unmatched
0,feature_engineered.monthly_sales_features,sales_analytics.monthly_sales,average_order_value,1,24,24
1,feature_engineered.monthly_sales_features,sales_analytics.monthly_sales,total_orders,24,0,0
2,feature_engineered.monthly_sales_features,analytics.customer_segmentation,average_delivery_days,1,24,49361
3,feature_engineered.monthly_sales_features,analytics.customer_segmentation,average_order_value,4,21,21359
4,feature_engineered.monthly_sales_features,analytics.customer_segmentation,average_review_score,2,23,9
5,feature_engineered.monthly_sales_features,analytics.customer_segmentation,total_orders,1,23,0
6,feature_engineered.monthly_sales_features,analytics.segment_feature_means,late_orders,1,22,1
7,feature_engineered.monthly_sales_features,feature_engineered.customer_features,average_delivery_days,1,24,49338
8,feature_engineered.monthly_sales_features,feature_engineered.customer_features,average_order_value,4,21,21264
9,feature_engineered.monthly_sales_features,feature_engineered.customer_features,average_review_score,2,23,10
10,feature_engineered.monthly_sales_features,feature_engineered.customer_features,total_orders,1,23,0
11,feature_engineered.monthly_sales_features,feature_engineered.order_features,purchase_month_start,25,0,0
12,feature_engineered.monthly_sales_features,feature_engineered.product_features,total_revenue,1,24,10309
13,feature_engineered.monthly_sales_features,feature_engineered.seller_features,total_items_sold,3,21,254
14,sales_analytics.monthly_sales,analytics.customer_segmentation,average_order_value,1,24,21362
15,sales_analytics.monthly_sales,analytics.customer_segmentation,total_orders,1,23,0
16,sales_analytics.monthly_sales,feature_engineered.customer_features,average_order_value,1,24,21267
17,sales_analytics.monthly_sales,feature_engineered.customer_features,total_orders,1,23,0
18,sales_analytics.monthly_sales,feature_engineered.order_features,total_freight_value,1,24,6129
19,sales_analytics.monthly_sales,feature_engineered.order_features,total_order_value,1,24,21232
20,sales_analytics.monthly_sales,feature_engineered.order_features,total_product_value,2,23,5447
21,analytics.clv_segment_summary,analytics.customer_lifetime_value,clv_segment,3,0,0
22,analytics.customer_segmentation,analytics.segment_distribution,cluster_id,2,0,0
23,analytics.customer_segmentation,analytics.segment_distribution,segment_name,2,0,0
24,analytics.customer_segmentation,analytics.segment_feature_means,cluster_id,2,0,0
25,analytics.customer_segmentation,analytics.segment_feature_means,late_orders,1,1,1
26,analytics.customer_segmentation,analytics.segment_feature_means,segment_name,2,0,0
27,analytics.customer_segmentation,analytics.segment_summary,cluster_id,2,0,0
28,analytics.customer_segmentation,analytics.segment_summary,segment_name,2,0,0
29,analytics.customer_segmentation,analytics.customer_lifetime_value,customer_id,50000,0,0
30,analytics.customer_segmentation,feature_engineered.customer_features,customer_id,25203,24797,24797
31,analytics.customer_segmentation,feature_engineered.order_features,customer_id,25222,24778,24778
32,analytics.segment_distribution,analytics.segment_feature_means,cluster_id,2,0,0
33,analytics.segment_distribution,analytics.segment_feature_means,segment_name,2,0,0
34,analytics.segment_distribution,analytics.segment_summary,cluster_id,2,0,0
35,analytics.segment_distribution,analytics.segment_summary,customer_count,2,0,0
36,analytics.segment_distribution,analytics.segment_summary,segment_name,2,0,0
37,analytics.segment_feature_means,analytics.segment_summary,cluster_id,2,0,0
38,analytics.segment_feature_means,analytics.segment_summary,segment_name,2,0,0
39,analytics.segment_feature_means,feature_engineered.customer_features,late_orders,1,1,1
40,analytics.customer_lifetime_value,feature_engineered.customer_features,customer_id,25203,24797,24797
41,analytics.customer_lifetime_value,feature_engineered.order_features,customer_id,25222,24778,24778
42,analytics.customer_churn_model_metrics,public.churn_model_comparison,model,1,0,1
43,analytics.customer_churn_predictions,feature_engineered.customer_features,customer_unique_id,25121,24879,23982
44,public.customer_churn_predictions,feature_engineered.customer_features,recency_days,1,626,49867
45,feature_engineered.category_features,feature_engineered.product_features,product_category_name,74,0,0
46,feature_engineered.category_features,feature_engineered.product_features,total_revenue,2,72,10308
47,feature_engineered.category_features,feature_engineered.seller_features,total_revenue,1,73,2777
48,feature_engineered.customer_features,feature_engineered.order_features,customer_id,25318,24682,24682

In [26]:
BUSINESS_DOMAINS = {
    "sales": [
        "sales",
        "revenue",
        "order",
        "payment"
    ],
    "forecast": [
        "forecast",
        "prediction",
        "future"
    ],
    "customer": [
        "customer"
    ],
    "churn": [
        "churn"
    ],
    "clv": [
        "clv",
        "lifetime"
    ],
    "recommendation": [
        "recommend"
    ],
    "segmentation": [
        "segment",
        "cluster"
    ],
    "product": [
        "product",
        "category"
    ],
    "review": [
        "review",
        "rating"
    ]
}


business_registry = {}

for table_name, dataframe in all_validated_tables.items():

    lower_name = table_name.lower()

    assigned = False

    for domain, keywords in BUSINESS_DOMAINS.items():

        if any(keyword in lower_name for keyword in keywords):

            business_registry.setdefault(domain, {})[table_name] = dataframe

            assigned = True

            break

    if not assigned:

        business_registry.setdefault(
            "other",
            {}
        )[table_name] = dataframe

print("Business Registry Created\n")

for domain, tables in business_registry.items():

    print(f"{domain.upper():20s}{len(tables)} table(s)")

Business Registry Created

SALES               6 table(s)
CLV                 3 table(s)
CUSTOMER            5 table(s)
SEGMENTATION        3 table(s)
FORECAST            2 table(s)
CHURN               1 table(s)
RECOMMENDATION      4 table(s)
PRODUCT             2 table(s)
OTHER               1 table(s)

In [27]:
registry_summary = []

for domain, tables in business_registry.items():

    for table_name, dataframe in tables.items():

        object_columns = dataframe.select_dtypes(
            include="object"
        ).columns.tolist()

        numeric_columns = dataframe.select_dtypes(
            include=np.number
        ).columns.tolist()

        datetime_columns = []

        for column in dataframe.columns:

            if (
                np.issubdtype(
                    dataframe[column].dtype,
                    np.datetime64
                )
                if dataframe[column].dtype != "object"
                else False
            ):
                datetime_columns.append(column)

        identifier_columns = [

            column

            for column in dataframe.columns

            if column.lower().endswith("_id")

        ]

        registry_summary.append({

            "domain": domain,

            "table": table_name,

            "rows": len(dataframe),

            "columns": len(dataframe.columns),

            "identifier_columns": len(identifier_columns),

            "numeric_columns": len(numeric_columns),

            "datetime_columns": len(datetime_columns),

            "object_columns": len(object_columns),

            "duplicate_rows": int(
                dataframe.duplicated().sum()
            ),

            "missing_values": int(
                dataframe.isna().sum().sum()
            )

        })

registry_summary = pd.DataFrame(registry_summary)

display(registry_summary)

,domain,table,rows,columns,identifier_columns,numeric_columns,datetime_columns,object_columns,duplicate_rows,missing_values
0,sales,feature_engineered.monthly_sales_features,25,11,0,10,1,0,0,0
1,sales,forecasting.future_sales_forecast,30,5,0,1,1,3,0,0
2,sales,forecasting.historical_sales_forecast,1299,6,0,2,1,3,0,0
3,sales,sales_analytics.monthly_sales,25,6,0,1,0,5,0,0
4,sales,sales_analytics.overall_sales_kpis,1,13,0,3,0,10,0,0
5,sales,feature_engineered.order_features,50000,35,2,23,6,6,0,0
6,clv,analytics.clv_segment_summary,3,9,0,8,0,1,0,0
7,clv,analytics.clv_overall_summary,9,2,0,0,0,2,0,0
8,clv,analytics.clv_validation,9,2,0,0,0,2,0,0
9,customer,analytics.customer_segmentation,50000,18,2,16,0,2,0,0
10,customer,analytics.customer_segmentation_model_evaluation,7,7,0,4,0,2,0,0
11,customer,analytics.customer_lifetime_value,50000,6,1,3,0,3,0,50000
12,customer,analytics.customer_churn_model_metrics,1,10,0,8,0,1,0,0
13,customer,feature_engineered.customer_features,50000,25,2,15,2,8,0,0
14,segmentation,analytics.segment_distribution,2,4,1,3,0,1,0,0
15,segmentation,analytics.segment_feature_means,2,13,1,12,0,1,0,0
16,segmentation,analytics.segment_summary,2,48,1,47,0,1,0,0
17,forecast,analytics.customer_churn_predictions,50000,9,1,4,1,4,0,0
18,forecast,public.customer_churn_predictions,50000,10,0,6,2,2,0,0
19,churn,public.churn_model_comparison,2,6,0,5,0,1,0,0
20,recommendation,recommendations.powerbi_product_recommendations,50000,13,2,3,1,9,0,0
21,recommendation,recommendations.product_recommendations,50000,7,2,3,0,4,0,0
22,recommendation,recommendations.recommendation_data_quality,8,3,0,0,0,3,0,0
23,recommendation,recommendations.recommendation_evaluation,1,6,0,1,0,5,0,4
24,product,feature_engineered.category_features,74,5,0,4,0,1,0,0
25,product,feature_engineered.product_features,32951,18,1,15,0,3,0,0
26,other,feature_engineered.seller_features,3095,10,1,7,0,3,0,0

In [28]:
business_kpis = {}

business_outputs = {

    "executive_summary": [],

    "business_insights": [],

    "business_recommendations": [],

    "risk_summary": [],

    "opportunity_summary": [],

    "forecast_summary": [],

    "customer_summary": [],

    "product_summary": []

}

print("=" * 80)
print("AI BUSINESS INSIGHTS ENGINE INITIALIZED")
print("=" * 80)

print(f"Business Domains : {len(business_registry)}")

print(f"Validated Tables : {len(all_validated_tables)}")

print(f"KPI Registry     : {len(business_kpis)}")

print(f"Output Objects   : {len(business_outputs)}")

================================================================================
AI BUSINESS INSIGHTS ENGINE INITIALIZED
================================================================================
Business Domains : 9
Validated Tables : 27
KPI Registry     : 0
Output Objects   : 8

In [29]:
def find_best_dataset(domain):

    datasets = business_registry.get(domain, {})

    if not datasets:
        return None, None

    ranked = sorted(
        datasets.items(),
        key=lambda x: (
            len(x[1]),
            len(x[1].columns)
        ),
        reverse=True
    )

    return ranked[0]


def normalize_column(column):

    return (
        str(column)
        .strip()
        .lower()
        .replace(" ", "_")
        .replace("-", "_")
    )


def find_columns(dataframe, keywords):

    matches = []

    for column in dataframe.columns:

        normalized = normalize_column(column)

        if any(
            keyword in normalized
            for keyword in keywords
        ):

            matches.append(column)

    return matches

In [30]:
sales_table_name, sales_df = find_best_dataset("sales")

if sales_df is None:

    print("No validated sales dataset discovered.")

else:

    revenue_columns = find_columns(

        sales_df,

        [

            "revenue",

            "payment",

            "price",

            "sales",

            "total",

            "value"

        ]

    )

    if revenue_columns:

        revenue_column = revenue_columns[0]

        total_revenue = pd.to_numeric(

            sales_df[revenue_column],

            errors="coerce"

        ).sum()

        business_kpis["total_revenue"] = float(total_revenue)

    order_columns = find_columns(

        sales_df,

        [

            "order_id"

        ]

    )

    if order_columns:

        business_kpis["order_count"] = int(

            sales_df[order_columns[0]]

            .nunique()

        )

    customer_columns = find_columns(

        sales_df,

        [

            "customer_id"

        ]

    )

    if customer_columns:

        business_kpis["customer_count"] = int(

            sales_df[customer_columns[0]]

            .nunique()

        )

display(
    pd.DataFrame(
        business_kpis.items(),
        columns=[
            "KPI",
            "Value"
        ]
    )
)

              KPI    Value
0   total_revenue  56564.0
1     order_count  50000.0
2  customer_count  50000.0

In [31]:
def add_kpi(
    name,
    value,
    business_area,
    source_table,
    confidence="Validated"
):
    business_kpis[name] = {
        "value": value,
        "business_area": business_area,
        "source_table": source_table,
        "confidence": confidence,
        "generated_at": CURRENT_TIMESTAMP
    }


def safe_numeric(series):

    return pd.to_numeric(
        series,
        errors="coerce"
    )


def first_existing(columns):

    if columns:
        return columns[0]

    return None

In [32]:
sales_table_name, sales_df = find_best_dataset("sales")

if sales_df is not None:

    revenue_column = first_existing(
        find_columns(
            sales_df,
            [
                "payment",
                "price",
                "revenue",
                "sales",
                "value",
                "total"
            ]
        )
    )

    if revenue_column is not None:

        revenue = safe_numeric(
            sales_df[revenue_column]
        )

        add_kpi(
            "total_revenue",
            float(revenue.sum()),
            "Sales",
            sales_table_name
        )

        add_kpi(
            "average_order_value",
            float(revenue.mean()),
            "Sales",
            sales_table_name
        )

        add_kpi(
            "median_order_value",
            float(revenue.median()),
            "Sales",
            sales_table_name
        )

        add_kpi(
            "maximum_order_value",
            float(revenue.max()),
            "Sales",
            sales_table_name
        )

        add_kpi(
            "minimum_order_value",
            float(revenue.min()),
            "Sales",
            sales_table_name
        )

print("Sales KPI Engine Complete")

Sales KPI Engine Complete

In [33]:
customer_table_name, customer_df = find_best_dataset(
    "customer"
)

if customer_df is not None:

    customer_column = first_existing(
        find_columns(
            customer_df,
            [
                "customer_id"
            ]
        )
    )

    if customer_column is not None:

        add_kpi(

            "total_customers",

            int(
                customer_df[
                    customer_column
                ].nunique()
            ),

            "Customer",

            customer_table_name

        )

    state_column = first_existing(
        find_columns(
            customer_df,
            [
                "state"
            ]
        )
    )

    if state_column is not None:

        add_kpi(

            "customer_regions",

            int(
                customer_df[
                    state_column
                ].nunique()
            ),

            "Customer",

            customer_table_name

        )

print("Customer KPI Engine Complete")

Customer KPI Engine Complete

In [34]:
product_table_name, product_df = find_best_dataset(
    "product"
)

if product_df is not None:

    product_column = first_existing(

        find_columns(

            product_df,

            [

                "product_id"

            ]

        )

    )

    if product_column is not None:

        add_kpi(

            "product_count",

            int(

                product_df[
                    product_column
                ].nunique()

            ),

            "Product",

            product_table_name

        )

    category_column = first_existing(

        find_columns(

            product_df,

            [

                "category"

            ]

        )

    )

    if category_column is not None:

        add_kpi(

            "category_count",

            int(

                product_df[
                    category_column
                ].nunique()

            ),

            "Product",

            product_table_name

        )

print("Product KPI Engine Complete")

Product KPI Engine Complete

In [35]:
forecast_table_name, forecast_df = find_best_dataset(
    "forecast"
)

if forecast_df is not None:

    forecast_column = first_existing(

        find_columns(

            forecast_df,

            [

                "forecast",

                "prediction",

                "expected"

            ]

        )

    )

    if forecast_column is not None:

        forecast_values = safe_numeric(

            forecast_df[
                forecast_column
            ]

        )

        add_kpi(

            "forecast_total",

            float(
                forecast_values.sum()
            ),

            "Forecast",

            forecast_table_name

        )

        add_kpi(

            "forecast_average",

            float(
                forecast_values.mean()
            ),

            "Forecast",

            forecast_table_name

        )

print("Forecast KPI Engine Complete")

Forecast KPI Engine Complete

In [36]:
churn_table_name, churn_df = find_best_dataset(
    "churn"
)

if churn_df is not None:

    churn_column = first_existing(

        find_columns(

            churn_df,

            [

                "churn"

            ]

        )

    )

    if churn_column is not None:

        churn_rate = (

            safe_numeric(
                churn_df[churn_column]
            )

            .mean()

            * 100

        )

        add_kpi(

            "overall_churn_rate",

            float(churn_rate),

            "Customer",

            churn_table_name

        )

print("Churn KPI Engine Complete")

Churn KPI Engine Complete

In [37]:
clv_table_name, clv_df = find_best_dataset(
    "clv"
)

if clv_df is not None:

    clv_column = first_existing(

        find_columns(

            clv_df,

            [

                "clv",

                "lifetime",

                "customer_value"

            ]

        )

    )

    if clv_column is not None:

        clv_values = safe_numeric(

            clv_df[
                clv_column
            ]

        )

        add_kpi(

            "average_clv",

            float(
                clv_values.mean()
            ),

            "Customer",

            clv_table_name

        )

        add_kpi(

            "maximum_clv",

            float(
                clv_values.max()
            ),

            "Customer",

            clv_table_name

        )

print("CLV KPI Engine Complete")

CLV KPI Engine Complete

In [38]:
recommendation_table_name, recommendation_df = find_best_dataset(
    "recommendation"
)

if recommendation_df is not None:

    add_kpi(

        "recommendation_records",

        len(recommendation_df),

        "Recommendation",

        recommendation_table_name

    )

    customer_columns = find_columns(

        recommendation_df,

        [

            "customer_id"

        ]

    )

    if customer_columns:

        add_kpi(

            "recommendation_coverage",

            int(

                recommendation_df[
                    customer_columns[0]
                ].nunique()

            ),

            "Recommendation",

            recommendation_table_name

        )

print("Recommendation KPI Engine Complete")

Recommendation KPI Engine Complete

In [40]:
records = []

for key, value in business_kpis.items():

    if isinstance(value, dict):

        record = {
            "kpi": key,
            **value
        }

    else:

        record = {

            "kpi": key,

            "value": value,

            "business_area": "Unknown",

            "source_table": None,

            "confidence": "Validated",

            "generated_at": CURRENT_TIMESTAMP

        }

    records.append(record)

business_kpi_df = pd.DataFrame(records)

if not business_kpi_df.empty:

    if "business_area" in business_kpi_df.columns:

        business_kpi_df = business_kpi_df.sort_values(
            "business_area"
        )

    business_kpi_df = business_kpi_df.reset_index(drop=True)

display(business_kpi_df)

print(f"Validated KPIs Generated : {len(business_kpi_df)}")

,kpi,value,business_area,source_table,confidence,generated_at
0,total_customers,50000.00000,Customer,feature_engineered.customer_features,Validated,2026-07-31 18:01:53.574094
1,customer_regions,27.00000,Customer,feature_engineered.customer_features,Validated,2026-07-31 18:01:53.574094
2,forecast_total,0.00000,Forecast,public.customer_churn_predictions,Validated,2026-07-31 18:01:53.574094
3,forecast_average,0.00000,Forecast,public.customer_churn_predictions,Validated,2026-07-31 18:01:53.574094
4,product_count,32951.00000,Product,feature_engineered.product_features,Validated,2026-07-31 18:01:53.574094
5,category_count,74.00000,Product,feature_engineered.product_features,Validated,2026-07-31 18:01:53.574094
6,recommendation_records,50000.00000,Recommendation,recommendations.powerbi_product_recommendations,Validated,2026-07-31 18:01:53.574094
7,recommendation_coverage,5000.00000,Recommendation,recommendations.powerbi_product_recommendations,Validated,2026-07-31 18:01:53.574094
8,total_revenue,56564.00000,Sales,feature_engineered.order_features,Validated,2026-07-31 18:01:53.574094
9,average_order_value,1.13128,Sales,feature_engineered.order_features,Validated,2026-07-31 18:01:53.574094
10,median_order_value,1.00000,Sales,feature_engineered.order_features,Validated,2026-07-31 18:01:53.574094
11,maximum_order_value,15.00000,Sales,feature_engineered.order_features,Validated,2026-07-31 18:01:53.574094
12,minimum_order_value,0.00000,Sales,feature_engineered.order_features,Validated,2026-07-31 18:01:53.574094
13,order_count,50000.00000,Unknown,None,Validated,2026-07-31 18:01:53.574094
14,customer_count,50000.00000,Unknown,None,Validated,2026-07-31 18:01:53.574094

Validated KPIs Generated : 15

In [41]:
insight_records = []

def add_insight(
    category,
    title,
    description,
    priority,
    confidence,
    source
):

    insight_records.append({

        "category": category,

        "title": title,

        "description": description,

        "priority": priority,

        "confidence": confidence,

        "source": source,

        "generated_at": CURRENT_TIMESTAMP

    })

print("Insight engine initialized.")

Insight engine initialized.

In [42]:
kpi_lookup = {}

for _, row in business_kpi_df.iterrows():

    kpi_lookup[row["kpi"]] = row["value"]

display(
    pd.DataFrame(
        list(kpi_lookup.items()),
        columns=["KPI", "Value"]
    )
)

                        KPI        Value
0           total_customers  50000.00000
1          customer_regions     27.00000
2            forecast_total      0.00000
3          forecast_average      0.00000
4             product_count  32951.00000
5            category_count     74.00000
6    recommendation_records  50000.00000
7   recommendation_coverage   5000.00000
8             total_revenue  56564.00000
9       average_order_value      1.13128
10       median_order_value      1.00000
11      maximum_order_value     15.00000
12      minimum_order_value      0.00000
13              order_count  50000.00000
14           customer_count  50000.00000

In [43]:
if "total_revenue" in kpi_lookup:

    revenue = float(kpi_lookup["total_revenue"])

    if revenue <= 0:

        add_insight(

            "Sales",

            "No Revenue",

            "Revenue is zero or negative. Validate sales data.",

            "High",

            "High",

            "Sales KPI"

        )

    else:

        add_insight(

            "Sales",

            "Revenue Available",

            f"Validated total revenue is {revenue:,.2f}.",

            "Low",

            "High",

            "Sales KPI"

        )

print("Sales insight completed.")

Sales insight completed.

In [44]:
if "average_order_value" in kpi_lookup:

    aov = float(kpi_lookup["average_order_value"])

    if aov > 0:

        add_insight(

            "Sales",

            "Average Order Value",

            f"Average order value is {aov:,.2f}.",

            "Medium",

            "High",

            "Sales KPI"

        )

In [45]:
if "overall_churn_rate" in kpi_lookup:

    churn = float(kpi_lookup["overall_churn_rate"])

    if churn >= 50:

        priority = "High"

    elif churn >= 20:

        priority = "Medium"

    else:

        priority = "Low"

    add_insight(

        "Customer",

        "Customer Churn",

        f"Overall churn rate is {churn:.2f}%",

        priority,

        "High",

        "Churn Model"

    )

In [46]:
if "average_clv" in kpi_lookup:

    clv = float(kpi_lookup["average_clv"])

    add_insight(

        "Customer",

        "Customer Lifetime Value",

        f"Average CLV is {clv:,.2f}.",

        "Medium",

        "High",

        "CLV Model"

    )

In [47]:
if "forecast_total" in kpi_lookup:

    forecast = float(kpi_lookup["forecast_total"])

    add_insight(

        "Forecast",

        "Forecast Revenue",

        f"Forecast revenue totals {forecast:,.2f}.",

        "Medium",

        "High",

        "Forecast Model"

    )

In [48]:
if "recommendation_records" in kpi_lookup:

    recommendations = int(
        kpi_lookup["recommendation_records"]
    )

    add_insight(

        "Recommendation",

        "Recommendation Engine",

        f"{recommendations:,} recommendation records are available.",

        "Low",

        "High",

        "Recommendation Engine"

    )

In [49]:
if "product_count" in kpi_lookup:

    products = int(kpi_lookup["product_count"])

    add_insight(

        "Product",

        "Product Catalog",

        f"{products:,} products are available for analysis.",

        "Low",

        "High",

        "Product Dataset"

    )

In [50]:
insight_df = pd.DataFrame(insight_records)

if not insight_df.empty:

    insight_df = insight_df.sort_values(

        [

            "priority",

            "category"

        ]

    ).reset_index(drop=True)

display(insight_df)

print(f"Insights Generated : {len(insight_df)}")

,category,title,description,priority,confidence,source,generated_at
0,Product,Product Catalog,"32,951 products are available for analysis.",Low,High,Product Dataset,2026-07-31 18:01:53.574094
1,Recommendation,Recommendation Engine,"50,000 recommendation records are available.",Low,High,Recommendation Engine,2026-07-31 18:01:53.574094
2,Sales,Revenue Available,"Validated total revenue is 56,564.00.",Low,High,Sales KPI,2026-07-31 18:01:53.574094
3,Forecast,Forecast Revenue,Forecast revenue totals 0.00.,Medium,High,Forecast Model,2026-07-31 18:01:53.574094
4,Sales,Average Order Value,Average order value is 1.13.,Medium,High,Sales KPI,2026-07-31 18:01:53.574094

Insights Generated : 5

In [51]:
priority_summary = (

    insight_df

    .groupby("priority")

    .size()

    .reset_index(name="count")

    .sort_values(

        "count",

        ascending=False

    )

)

display(priority_summary)

  priority  count
0      Low      3
1   Medium      2

In [52]:
executive_summary = []

if insight_df.empty:

    executive_summary.append({

        "summary_type": "Information",

        "message": "No business insights were generated.",

        "priority": "Low"

    })

else:

    executive_summary.append({

        "summary_type": "Overview",

        "message": (
            f"{len(insight_df)} validated AI insights were generated "
            f"across {insight_df['category'].nunique()} business domains."
        ),

        "priority": "Information"

    })

    executive_summary.append({

        "summary_type": "High Priority",

        "message": (
            f"{(insight_df['priority']=='High').sum()} high-priority insights detected."
        ),

        "priority": "High"

    })

executive_summary_df = pd.DataFrame(executive_summary)

display(executive_summary_df)

,summary_type,message,priority
0,Overview,5 validated AI insights were generated across 4 business domains.,Information
1,High Priority,0 high-priority insights detected.,High

In [53]:
risk_records = []

high_priority = insight_df[
    insight_df["priority"] == "High"
]

for _, row in high_priority.iterrows():

    risk_records.append({

        "risk_category": row["category"],

        "risk": row["title"],

        "description": row["description"],

        "confidence": row["confidence"],

        "recommended_action":
            "Immediate investigation recommended."

    })

business_risk_df = pd.DataFrame(risk_records)

display(business_risk_df)

Empty DataFrame
Columns: []
Index: []

In [54]:
opportunity_records = []

medium_low = insight_df[
    insight_df["priority"].isin(
        ["Medium", "Low"]
    )
]

for _, row in medium_low.iterrows():

    opportunity_records.append({

        "business_area": row["category"],

        "opportunity": row["title"],

        "description": row["description"],

        "confidence": row["confidence"]

    })

business_opportunity_df = pd.DataFrame(
    opportunity_records
)

display(business_opportunity_df)

,business_area,opportunity,description,confidence
0,Product,Product Catalog,"32,951 products are available for analysis.",High
1,Recommendation,Recommendation Engine,"50,000 recommendation records are available.",High
2,Sales,Revenue Available,"Validated total revenue is 56,564.00.",High
3,Forecast,Forecast Revenue,Forecast revenue totals 0.00.,High
4,Sales,Average Order Value,Average order value is 1.13.,High

In [55]:
recommended_actions = []

for _, row in insight_df.iterrows():

    action = "Continue monitoring."

    if row["priority"] == "High":

        action = "Immediate business review recommended."

    elif row["priority"] == "Medium":

        action = "Review during the next planning cycle."

    recommended_actions.append({

        "category": row["category"],

        "finding": row["title"],

        "priority": row["priority"],

        "recommended_action": action

    })

recommended_actions_df = pd.DataFrame(
    recommended_actions
)

display(recommended_actions_df)

,category,finding,priority,recommended_action
0,Product,Product Catalog,Low,Continue monitoring.
1,Recommendation,Recommendation Engine,Low,Continue monitoring.
2,Sales,Revenue Available,Low,Continue monitoring.
3,Forecast,Forecast Revenue,Medium,Review during the next planning cycle.
4,Sales,Average Order Value,Medium,Review during the next planning cycle.

In [56]:
management_report = {

    "report_generated": CURRENT_TIMESTAMP,

    "business_domains": int(
        insight_df["category"].nunique()
    ),

    "total_kpis": len(business_kpi_df),

    "total_insights": len(insight_df),

    "high_priority": int(
        (insight_df["priority"] == "High").sum()
    ),

    "medium_priority": int(
        (insight_df["priority"] == "Medium").sum()
    ),

    "low_priority": int(
        (insight_df["priority"] == "Low").sum()
    )

}

management_report_df = pd.DataFrame(
    [management_report]
)

display(management_report_df)

,report_generated,business_domains,total_kpis,total_insights,high_priority,medium_priority,low_priority
0,2026-07-31 18:01:53.574094,4,15,5,0,2,3

In [57]:
business_outputs["executive_summary"] = executive_summary_df

business_outputs["risk_summary"] = business_risk_df

business_outputs["opportunity_summary"] = business_opportunity_df

business_outputs["business_recommendations"] = (
    recommended_actions_df
)

business_outputs["business_insights"] = insight_df

business_outputs["management_report"] = (
    management_report_df
)

print("Business output registry updated.")

Business output registry updated.

In [58]:
output_registry_summary = []

for name, dataframe in business_outputs.items():

    if isinstance(dataframe, pd.DataFrame):

        output_registry_summary.append({

            "output_name": name,

            "rows": len(dataframe),

            "columns": len(dataframe.columns)

        })

output_registry_summary_df = pd.DataFrame(
    output_registry_summary
)

display(output_registry_summary_df)

                output_name  rows  columns
0         executive_summary     2        3
1         business_insights     5        7
2  business_recommendations     5        4
3              risk_summary     0        0
4       opportunity_summary     5        4
5         management_report     1        7

In [59]:
print("=" * 80)
print("EXECUTIVE AI INSIGHTS SUMMARY")
print("=" * 80)

print(f"Business KPIs Generated : {len(business_kpi_df)}")

print(f"Insights Generated      : {len(insight_df)}")

print(f"Business Risks          : {len(business_risk_df)}")

print(f"Business Opportunities  : {len(business_opportunity_df)}")

print(f"Recommended Actions     : {len(recommended_actions_df)}")

print("=" * 80)

================================================================================
EXECUTIVE AI INSIGHTS SUMMARY
================================================================================
Business KPIs Generated : 15
Insights Generated      : 5
Business Risks          : 0
Business Opportunities  : 5
Recommended Actions     : 5
================================================================================

In [60]:
EXPORT_SCHEMA = "ai_insights"

with engine.begin() as connection:

    connection.execute(
        text(
            f"""
            CREATE SCHEMA IF NOT EXISTS {EXPORT_SCHEMA};
            """
        )
    )

print(f"Schema '{EXPORT_SCHEMA}' is ready.")

Schema 'ai_insights' is ready.

In [61]:
export_tables = {

    "business_kpis": business_kpi_df,

    "business_insights": insight_df,

    "executive_summary": executive_summary_df,

    "business_risks": business_risk_df,

    "business_opportunities": business_opportunity_df,

    "recommended_actions": recommended_actions_df,

    "management_report": management_report_df

}

display(
    pd.DataFrame(
        {
            "table_name": export_tables.keys(),
            "rows": [len(df) for df in export_tables.values()]
        }
    )
)

               table_name  rows
0           business_kpis    15
1       business_insights     5
2       executive_summary     2
3          business_risks     0
4  business_opportunities     5
5     recommended_actions     5
6       management_report     1

In [62]:
export_log = []

for table_name, dataframe in export_tables.items():

    try:

        dataframe.to_sql(

            name=table_name,

            con=engine,

            schema=EXPORT_SCHEMA,

            if_exists="replace",

            index=False,

            method="multi"

        )

        export_log.append({

            "table": table_name,

            "status": "Success",

            "rows": len(dataframe)

        })

    except Exception as error:

        export_log.append({

            "table": table_name,

            "status": "Failed",

            "rows": 0,

            "error": str(error)

        })

export_log_df = pd.DataFrame(export_log)

display(export_log_df)

                    table   status  rows
0           business_kpis  Success    15
1       business_insights  Success     5
2       executive_summary  Success     2
3          business_risks  Success     0
4  business_opportunities  Success     5
5     recommended_actions  Success     5
6       management_report  Success     1

In [63]:
successful_exports = export_log_df[
    export_log_df["status"] == "Success"
]

failed_exports = export_log_df[
    export_log_df["status"] == "Failed"
]

print(f"Successful Exports : {len(successful_exports)}")
print(f"Failed Exports     : {len(failed_exports)}")

if not failed_exports.empty:

    display(failed_exports)

Successful Exports : 7
Failed Exports     : 0

In [64]:
powerbi_tables = {}

powerbi_tables["powerbi_business_kpis"] = business_kpi_df.copy()

powerbi_tables["powerbi_business_insights"] = insight_df.copy()

powerbi_tables["powerbi_management_report"] = management_report_df.copy()

powerbi_tables["powerbi_recommended_actions"] = recommended_actions_df.copy()

print(f"Prepared {len(powerbi_tables)} Power BI tables.")

Prepared 4 Power BI tables.

In [65]:
powerbi_export_log = []

for table_name, dataframe in powerbi_tables.items():

    try:

        dataframe.to_sql(

            name=table_name,

            con=engine,

            schema=EXPORT_SCHEMA,

            if_exists="replace",

            index=False,

            method="multi"

        )

        powerbi_export_log.append({

            "table": table_name,

            "status": "Success",

            "rows": len(dataframe)

        })

    except Exception as error:

        powerbi_export_log.append({

            "table": table_name,

            "status": "Failed",

            "rows": 0,

            "error": str(error)

        })

powerbi_export_log_df = pd.DataFrame(
    powerbi_export_log
)

display(powerbi_export_log_df)

                         table   status  rows
0        powerbi_business_kpis  Success    15
1    powerbi_business_insights  Success     5
2    powerbi_management_report  Success     1
3  powerbi_recommended_actions  Success     5

In [66]:
all_exports = pd.concat(

    [

        export_log_df.assign(export_type="Business"),

        powerbi_export_log_df.assign(export_type="PowerBI")

    ],

    ignore_index=True

)

display(all_exports)

                          table   status  rows export_type
0                 business_kpis  Success    15    Business
1             business_insights  Success     5    Business
2             executive_summary  Success     2    Business
3                business_risks  Success     0    Business
4        business_opportunities  Success     5    Business
5           recommended_actions  Success     5    Business
6             management_report  Success     1    Business
7         powerbi_business_kpis  Success    15     PowerBI
8     powerbi_business_insights  Success     5     PowerBI
9     powerbi_management_report  Success     1     PowerBI
10  powerbi_recommended_actions  Success     5     PowerBI

In [67]:
summary_statistics = {

    "generated_at": CURRENT_TIMESTAMP,

    "business_tables": len(export_tables),

    "powerbi_tables": len(powerbi_tables),

    "successful_exports": int(
        (all_exports["status"] == "Success").sum()
    ),

    "failed_exports": int(
        (all_exports["status"] == "Failed").sum()
    )

}

summary_statistics_df = pd.DataFrame(
    [summary_statistics]
)

display(summary_statistics_df)

,generated_at,business_tables,powerbi_tables,successful_exports,failed_exports
0,2026-07-31 18:01:53.574094,7,4,11,0

In [68]:
summary_statistics_df.to_sql(

    name="export_summary",

    con=engine,

    schema=EXPORT_SCHEMA,

    if_exists="replace",

    index=False

)

print("Export summary saved.")

Export summary saved.

In [69]:
print("=" * 80)
print("POSTGRESQL EXPORT COMPLETE")
print("=" * 80)

print(f"Business Tables : {len(export_tables)}")

print(f"Power BI Tables : {len(powerbi_tables)}")

print(
    f"Successful Exports : "
    f"{(all_exports['status']=='Success').sum()}"
)

print(
    f"Failed Exports : "
    f"{(all_exports['status']=='Failed').sum()}"
)

print("=" * 80)

================================================================================
POSTGRESQL EXPORT COMPLETE
================================================================================
Business Tables : 7
Power BI Tables : 4
Successful Exports : 11
Failed Exports : 0
================================================================================

In [70]:
validation_results = []

required_outputs = {

    "Business KPIs": business_kpi_df,

    "Business Insights": insight_df,

    "Executive Summary": executive_summary_df,

    "Business Risks": business_risk_df,

    "Business Opportunities": business_opportunity_df,

    "Recommended Actions": recommended_actions_df,

    "Management Report": management_report_df

}

for name, dataframe in required_outputs.items():

    validation_results.append({

        "artifact": name,

        "exists": dataframe is not None,

        "rows": len(dataframe),

        "columns": len(dataframe.columns),

        "empty": dataframe.empty

    })

validation_results_df = pd.DataFrame(validation_results)

display(validation_results_df)

                 artifact  exists  rows  columns  empty
0           Business KPIs    True    15        6  False
1       Business Insights    True     5        7  False
2       Executive Summary    True     2        3  False
3          Business Risks    True     0        0   True
4  Business Opportunities    True     5        4  False
5     Recommended Actions    True     5        4  False
6       Management Report    True     1        7  False

In [71]:
validation_results_df["status"] = np.where(

    validation_results_df["empty"],

    "Warning",

    "Passed"

)

validation_summary = validation_results_df.groupby(

    "status"

).size().reset_index(name="count")

display(validation_summary)

    status  count
0   Passed      6
1  Warning      1

In [72]:
data_quality_summary = []

for table_name, dataframe in export_tables.items():

    duplicate_rows = int(dataframe.duplicated().sum())

    missing_values = int(dataframe.isna().sum().sum())

    completeness = round(

        (

            1 -

            (

                missing_values /

                max(dataframe.shape[0] * max(dataframe.shape[1], 1), 1)

            )

        ) * 100,

        2

    )

    data_quality_summary.append({

        "table": table_name,

        "rows": len(dataframe),

        "columns": len(dataframe.columns),

        "duplicate_rows": duplicate_rows,

        "missing_values": missing_values,

        "completeness_percent": completeness

    })

data_quality_df = pd.DataFrame(data_quality_summary)

display(data_quality_df)

,table,rows,columns,duplicate_rows,missing_values,completeness_percent
0,business_kpis,15,6,0,2,97.78
1,business_insights,5,7,0,0,100.00
2,executive_summary,2,3,0,0,100.00
3,business_risks,0,0,0,0,100.00
4,business_opportunities,5,4,0,0,100.00
5,recommended_actions,5,4,0,0,100.00
6,management_report,1,7,0,0,100.00

In [73]:
project_metrics = {

    "execution_timestamp": CURRENT_TIMESTAMP,

    "validated_source_tables": len(all_validated_tables),

    "business_domains": len(business_registry),

    "generated_kpis": len(business_kpi_df),

    "generated_insights": len(insight_df),

    "postgres_exports": len(successful_exports),

    "powerbi_exports": len(powerbi_tables)

}

project_metrics_df = pd.DataFrame(

    [project_metrics]

)

display(project_metrics_df)

,execution_timestamp,validated_source_tables,business_domains,generated_kpis,generated_insights,postgres_exports,powerbi_exports
0,2026-07-31 18:01:53.574094,27,9,15,5,7,4

In [74]:
try:

    validation_results_df.to_sql(

        "validation_results",

        engine,

        schema=EXPORT_SCHEMA,

        if_exists="replace",

        index=False

    )

    data_quality_df.to_sql(

        "data_quality_summary",

        engine,

        schema=EXPORT_SCHEMA,

        if_exists="replace",

        index=False

    )

    project_metrics_df.to_sql(

        "project_metrics",

        engine,

        schema=EXPORT_SCHEMA,

        if_exists="replace",

        index=False

    )

    print("Validation reports exported successfully.")

except Exception as error:

    print(error)

Validation reports exported successfully.

In [75]:
completion_checklist = pd.DataFrame({

    "Module": [

        "Dataset Discovery",

        "Dataset Validation",

        "Business Registry",

        "KPI Engine",

        "Insight Engine",

        "Executive Summary",

        "Risk Analysis",

        "Opportunity Analysis",

        "Recommendations",

        "PostgreSQL Export",

        "Power BI Preparation",

        "Validation"

    ],

    "Completed": [

        True,

        True,

        True,

        True,

        True,

        True,

        True,

        True,

        True,

        True,

        True,

        True

    ]

})

display(completion_checklist)

                  Module  Completed
0      Dataset Discovery       True
1     Dataset Validation       True
2      Business Registry       True
3             KPI Engine       True
4         Insight Engine       True
5      Executive Summary       True
6          Risk Analysis       True
7   Opportunity Analysis       True
8        Recommendations       True
9      PostgreSQL Export       True
10  Power BI Preparation       True
11            Validation       True

In [76]:
completion_percentage = round(

    (

        completion_checklist["Completed"]

        .sum()

        /

        len(completion_checklist)

    ) * 100,

    2

)

print(f"Notebook Completion : {completion_percentage}%")

Notebook Completion : 100.0%

In [77]:
final_statistics = {

    "Business KPI Records":

        len(business_kpi_df),

    "Business Insight Records":

        len(insight_df),

    "Executive Summary Records":

        len(executive_summary_df),

    "Risk Records":

        len(business_risk_df),

    "Opportunity Records":

        len(business_opportunity_df),

    "Recommendation Records":

        len(recommended_actions_df)

}

final_statistics_df = pd.DataFrame(

    list(final_statistics.items()),

    columns=[

        "Metric",

        "Value"

    ]

)

display(final_statistics_df)

                      Metric  Value
0       Business KPI Records     15
1   Business Insight Records      5
2  Executive Summary Records      2
3               Risk Records      0
4        Opportunity Records      5
5     Recommendation Records      5

In [78]:
print("=" * 100)

print("NOTEBOOK 14 - AI INSIGHTS")

print("=" * 100)

print("Business Intelligence Pipeline Completed Successfully")

print(f"Generated KPIs           : {len(business_kpi_df)}")

print(f"Generated Insights       : {len(insight_df)}")

print(f"Business Risks           : {len(business_risk_df)}")

print(f"Business Opportunities   : {len(business_opportunity_df)}")

print(f"Recommended Actions      : {len(recommended_actions_df)}")

print(f"PostgreSQL Schema        : {EXPORT_SCHEMA}")

print(f"Completion Percentage    : {completion_percentage}%")

print("=" * 100)

====================================================================================================
NOTEBOOK 14 - AI INSIGHTS
====================================================================================================
Business Intelligence Pipeline Completed Successfully
Generated KPIs           : 15
Generated Insights       : 5
Business Risks           : 0
Business Opportunities   : 5
Recommended Actions      : 5
PostgreSQL Schema        : ai_insights
Completion Percentage    : 100.0%
====================================================================================================